### ISSUE TITLE
Failed when running yarn example: "main" java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestampsAndCacheVisibilities

### ISSUE THREAD

**Issue by Sherler** [Angel-ML/angel#1041]
submit  ./angel-submit in yarn mode，failed with the following logs：
Hope someone can help me figure out what is happening...
```bash
20/11/19 08:12:24 INFO client.AngelClient: stop the application
20/11/19 08:12:24 INFO client.AngelClient: master is null, just kill the application
20/11/19 08:12:24 ERROR yarn.AngelYarnClient: kill application failed, 
org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException: Trying to kill an absent application application_1605748190027_18081
        at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.forceKillApplication(ClientRMService.java:639)
        at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.forceKillApplication(ApplicationClientProtocolPBServiceImpl.java:155)
        at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:405)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:629)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1095)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2212)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1865)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2210)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.yarn.ipc.RPCUtil.instantiateException(RPCUtil.java:53)
        at org.apache.hadoop.yarn.ipc.RPCUtil.unwrapAndThrowException(RPCUtil.java:101)
        at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.forceKillApplication(ApplicationClientProtocolPBClientImpl.java:175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
        at com.sun.proxy.$Proxy8.forceKillApplication(Unknown Source)
        at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.killApplication(YarnClientImpl.java:420)
        at com.tencent.angel.client.yarn.AngelYarnClient.kill(AngelYarnClient.java:183)
        at com.tencent.angel.client.AngelClient.stop(AngelClient.java:487)
        at com.tencent.angel.client.AngelClient.stop(AngelClient.java:494)
        at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:69)
        at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:88)
        at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:29)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:91)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:77)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1863)
        at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:77)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:44)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException): Trying to kill an absent application application_1605748190027_18081
        at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.forceKillApplication(ClientRMService.java:639)
        at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.forceKillApplication(ApplicationClientProtocolPBServiceImpl.java:155)
        at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:405)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:629)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1095)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2212)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1865)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2210)

        at org.apache.hadoop.ipc.Client.call(Client.java:1472)
        at org.apache.hadoop.ipc.Client.call(Client.java:1409)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:242)
        at com.sun.proxy.$Proxy7.forceKillApplication(Unknown Source)
        at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.forceKillApplication(ApplicationClientProtocolPBClientImpl.java:172)
        ... 21 more
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestampsAndCacheVisibilities(Lorg/apache/hadoop/conf/Configuration;)V
        at com.tencent.angel.client.yarn.AngelYarnClient.copyAndConfigureFiles(AngelYarnClient.java:287)
        at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:153)
        at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:55)
        at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:88)
        at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:29)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:91)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:77)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1863)
        at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:77)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:44)
```

`${ANGEL_HOME}/lib/hadoop-mapreduce-client-core-2.7.3.jar` has been added to angle-site.xml

**Comment by Sherler** [comment]
solved it on my own:
As the hadoop version on my host is 2.6.0, the corresponding jar does not include the methods. By replacing the `hadoop-mapreduce-client-core-2.6.0.jar` at '/usr/lib/hadoop-mapreduce/' with the jar in `${ANGLE_HOME}/lib/hadoop-mapreduce-client-core-2.7.3.jar`, I get rid of the error .
