### ISSUE TITLE
Failed on running: ./angel-example com.tencent.angel.spark.examples.local.Word2vecExample

### ISSUE THREAD

**Issue by catordog-byte** [Angel-ML/angel#1053]
Running on Mac local, Angel version: v3.1.0
```
Caused by: com.tencent.angel.exception.PSRPCException: Sub-Task 0 execution failed, failed message=get row split fatal error happened get udf request GetUDFRequest{getFuncClass='com.tencent.angel.graph.embedding.line.LINEGetEmbedding', partParam=PartitionGetParam{matrixId=1, partKey=PartitionKey(matrixId=1, partitionId=3, startRow=0, startCol=10788, endRow=1, endCol=14384)indexNum=-1)}} PartitionRequest{clock=0, partKey=PartitionKey(matrixId=1, partitionId=3, startRow=0, startCol=10788, endRow=1, endCol=14384)indexNum=-1), comeFromPs=false} com.tencent.angel.ps.server.data.request.GetUDFRequest@e failed java.lang.NullPointerException
	at com.tencent.angel.graph.embedding.line.LINEGetEmbedding$$anonfun$partitionGet$1.apply(LINEGetEmbedding.scala:80)
	at com.tencent.angel.graph.embedding.line.LINEGetEmbedding$$anonfun$partitionGet$1.apply(LINEGetEmbedding.scala:79)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofInt.foreach(ArrayOps.scala:234)
	at com.tencent.angel.graph.embedding.line.LINEGetEmbedding.partitionGet(LINEGetEmbedding.scala:79)
	at com.tencent.angel.ps.server.data.WorkerPool.getSplit(WorkerPool.java:1140)
	at com.tencent.angel.ps.server.data.WorkerPool.handleRPC(WorkerPool.java:1029)
	at com.tencent.angel.ps.server.data.WorkerPool.handle(WorkerPool.java:683)
	at com.tencent.angel.ps.server.data.WorkerPool.access$100(WorkerPool.java:91)
	at com.tencent.angel.ps.server.data.WorkerPool$Processor.run(WorkerPool.java:413)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	... 9 more
```

**Comment by ouyangwen-it** [comment]
你数据和设置的算法参数是什么样你的呢

**Comment by ouyangwen-it** [comment]
跑cluster目录下的word2vec看看
