### ISSUE TITLE
Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project angel-ps-core

### ISSUE THREAD

**Issue by BirderEric** [Angel-ML/angel#1056]
---
name: Bug report/Feature request/Question
about: Create a report to help us improve
title:  安装angel2.4.0版本编译失败
label: bug/enhancement/question
assignees: ''
---
WARNING]   def parmap[I, O, Col[X] <: TraversableLike[X, Col[X]]]
[WARNING]                    ^
[WARNING] one warning found
[DEBUG] Scala compilation took 39.2254568 s
[DEBUG] Attempting to call javac directly...
[DEBUG] com.sun.tools.javac.Main not found with appropriate method signature; forking javac instead
[DEBUG] Forking javac: javac @/tmp/sbt_1a8ffcea/argfile
[DEBUG] javac returned exit code: 137
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] angel .............................................. SUCCESS [  0.588 s]
[INFO] angel-ps ........................................... SUCCESS [ 14.227 s]
[INFO] angel-ps-core ...................................... FAILURE [01:00 min]
[INFO] angel-ps-psf ....................................... SKIPPED
[INFO] angel-ps-graph ..................................... SKIPPED
[INFO] angel-ps-tools ..................................... SKIPPED
[INFO] angel-ps-mllib ..................................... SKIPPED
[INFO] angel-ps-examples .................................. SKIPPED
[INFO] spark-on-angel ..................................... SKIPPED
[INFO] spark-on-angel-core ................................ SKIPPED
[INFO] spark-on-angel-mllib ............................... SKIPPED
[INFO] spark-on-angel-examples ............................ SKIPPED
[INFO] angel-dist ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:16 min
[INFO] Finished at: 2021-01-15T10:09:34+00:00
[INFO] Final Memory: 32M/567M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project angel-ps-core: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed. CompileFailed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project angel-ps-core: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: javac returned nonzero exit code
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:77)
	at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:35)
	at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:63)
	at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:21)
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:63)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply$mcV$sp(AggressiveCompile.scala:127)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:127)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:127)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:166)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileJava$1(AggressiveCompile.scala:126)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:143)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:87)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:39)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:37)
	at sbt.inc.IncrementalCommon.cycle(Incremental.scala:99)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:37)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:65)
	at sbt.inc.Incremental$.compile(Incremental.scala:37)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:27)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:157)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:71)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:184)
	at com.typesafe.zinc.Compiler.compile(Compiler.scala:164)
	at sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:92)
	at scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:303)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:119)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :angel-ps-core

**Environment**:
- Java version:1.8
- Scala version:2.11.8
- Spark version: 2.4.7
- maven:3.3.9
- angel version :2.4.0
- OS and version:ubuntu 16.04

**Comment by ouyangwen-it** [comment]
> ## name: Bug report/Feature request/Question
> about: Create a report to help us improve
> title: 安装angel2.4.0版本编译失败
> label: bug/enhancement/question
> assignees: ''
> WARNING] def parmap[I, O, Col[X] <: TraversableLike[X, Col[X]]]
> [WARNING] ^
> [WARNING] one warning found
> [DEBUG] Scala compilation took 39.2254568 s
> [DEBUG] Attempting to call javac directly...
> [DEBUG] com.sun.tools.javac.Main not found with appropriate method signature; forking javac instead
> [DEBUG] Forking javac: javac @/tmp/sbt_1a8ffcea/argfile
> [DEBUG] javac returned exit code: 137
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] angel .............................................. SUCCESS [ 0.588 s]
> [INFO] angel-ps ........................................... SUCCESS [ 14.227 s]
> [INFO] angel-ps-core ...................................... FAILURE [01:00 min]
> [INFO] angel-ps-psf ....................................... SKIPPED
> [INFO] angel-ps-graph ..................................... SKIPPED
> [INFO] angel-ps-tools ..................................... SKIPPED
> [INFO] angel-ps-mllib ..................................... SKIPPED
> [INFO] angel-ps-examples .................................. SKIPPED
> [INFO] spark-on-angel ..................................... SKIPPED
> [INFO] spark-on-angel-core ................................ SKIPPED
> [INFO] spark-on-angel-mllib ............................... SKIPPED
> [INFO] spark-on-angel-examples ............................ SKIPPED
> [INFO] angel-dist ......................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:16 min
> [INFO] Finished at: 2021-01-15T10:09:34+00:00
> [INFO] Final Memory: 32M/567M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project angel-ps-core: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed. CompileFailed -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project angel-ps-core: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
> at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
> at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.
> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
> ... 19 more
> Caused by: javac returned nonzero exit code
> at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:77)
> at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:35)
> at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:63)
> at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:21)
> at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:63)
> at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply$mcV$sp(AggressiveCompile.scala:127)
> at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:127)
> at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:127)
> at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:166)
> at sbt.compiler.AggressiveCompile$$anonfun$3.compileJava$1(AggressiveCompile.scala:126)
> at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:143)
> at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:87)
> at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:39)
> at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:37)
> at sbt.inc.IncrementalCommon.cycle(Incremental.scala:99)
> at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
> at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:37)
> at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:65)
> at sbt.inc.Incremental$.compile(Incremental.scala:37)
> at sbt.inc.IncrementalCompile$.apply(Compile.scala:27)
> at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:157)
> at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:71)
> at com.typesafe.zinc.Compiler.compile(Compiler.scala:184)
> at com.typesafe.zinc.Compiler.compile(Compiler.scala:164)
> at sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:92)
> at scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:303)
> at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:119)
> at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:99)
> at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:482)
> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
> ... 20 more
> [ERROR]
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :angel-ps-core
> 
> **Environment**:
> 
> * Java version:1.8
> * Scala version:2.11.8
> * Spark version: 2.4.7
> * maven:3.3.9
> * angel version :2.4.0
> * OS and version:ubuntu 16.04

![image](https://user-images.githubusercontent.com/13943417/104898244-5467b480-59b4-11eb-9441-814c103ca7c9.png)
看这日志的退出码像是编译的时候内存不够呢(out of memory)

**Comment by BirderEric** [comment]
感谢，我想问下大佬，要使用GCN/GRAPHSAGE这类图算法，安装的angel的版本是2.4.0还是可以master？

**Comment by ouyangwen-it** [comment]
> 感谢，我想问下大佬，要使用GCN/GRAPHSAGE这类图算法，安装的angel的版本是2.4.0还是可以master？

使用master分支即可
