### ISSUE TITLE
Init AngelPSContext fail, please check logs of master of angel

### ISSUE THREAD

**Issue by graphv** [Angel-ML/angel#1129]

**Comment by graphv** [comment]
Exception in thread "main" org.apache.spark.SparkException: Application application_1625556165992_9246 finished with failed status
		at org.apache.spark.deploy.yarn.Client.run(Client.scala:1269)
		at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1627)
		at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:904)
		at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
		at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	21/07/13 19:15:53 INFO ShutdownHookManager: Shutdown hook called
	21/07/13 19:15:53 INFO ShutdownHookManager: Deleting directory /tmp/spark-eedd318a-70ff-4b0a-accd-9116afd734c7
	21/07/13 19:15:53 INFO ShutdownHookManager: Deleting directory /tmp/spark-35ceb4d9-5f81-419b-a6b3-e25623ac6625

**Comment by graphv** [comment]
local模式可以运行，cluster模式失败
Application application_1625556165992_9281 failed 2 times due to AM Container for appattempt_1625556165992_9281_000002 exited with exitCode: -1000
Failing this attempt.Diagnostics: [2021-07-13 20:22:16.533]File does not exist: hdfs://a:8020/tmp/hadoop-yarn/hdfs/.staging/application_1625556165992_9281/job.xml
java.io.FileNotFoundException: File does not exist: hdfs://a:8020/tmp/hadoop-yarn/hdfs/.staging/application_1625556165992_9281/job.xml
at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1587)
at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1580)
at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1595)
at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:269)
at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:67)
at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:414)
at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:411)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:411)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.doDownloadCall(ContainerLocalizer.java:242)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:235)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ContainerLocalizer$FSDownloadWrapper.call(ContainerLocalizer.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
For more detailed output, check the application tracking page: http://a:8088/cluster/app/application_1625556165992_9281 Then click on links to logs of each attempt.
. Failing the application.
