### ISSUE TITLE
at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)

### ISSUE THREAD

**Issue by graphv** [Angel-ML/angel#1134]
```
at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
21/07/20 16:57:08 INFO ShutdownHookManager: Shutdown hook called
21/07/20 16:57:08 INFO PSAgent: stop heartbeat thread!
21/07/20 16:57:08 INFO PSAgent: stop user request adapater
21/07/20 16:57:08 INFO PSAgent: stop rpc dispacher
21/07/20 16:57:08 INFO ChannelManager2: Channel manager stop
```

**Comment by graphv** [comment]
```
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
		at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
		at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
		at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
		at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
		at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479)
		at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	21/07/20 17:04:14 INFO CoarseGrainedExecutorBackend: Got assigned task 93931
	21/07/20 17:04:14 INFO Executor: Running task 5.3 in stage 1872.1 (TID 93931)
```

**Comment by ouyangwen-it** [comment]
提issue麻烦按照我们的模板来提(建issue的时候有相关描述)，说明使用的版本，什么算法，具体遇到什问题，直接贴个无头无尾的日志很难定位问题
