### ISSUE TITLE
ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker for task 8642,5,main] java.lang.StackOverflowError

### ISSUE THREAD

**Issue by DeepWalk** [Angel-ML/angel#1136]
```
ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker for task 8642,5,main]
java.lang.StackOverflowError
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2679)
	at java.io.ObjectInputStream$BlockDataInputStream.readUnsignedShort(ObjectInputStream.java:3168)
	at java.io.ObjectInputStream$BlockDataInputStream.readUTF(ObjectInputStream.java:3226)
	at java.io.ObjectInputStream.readUTF(ObjectInputStream.java:1133)
	at java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:768)
	at java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:891)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1857)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1975)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
```

**Comment by ouyangwen-it** [comment]
请参考提issue的格式：
**Environment**:
- Java version:
- Scala version:
- Spark version:
- PyTorch and Python version:
- OS and version:


**Checklist**:
- Did you check if your bug/feature/question is answered in the FQA ?
- Did you search issues to find if somebody discuss your bug/feature/question before?
- If your bug/question is about install, did you read [this doc](../docs/deploy/source_compile_en.md)?
- If your bug/question is about parameter setting, did you read [this doc](../docs/deploy/config_details_en.md)?


**Your Bug/Feature request/Question**: Please describe bug/enhancement/question in detail. 
- For bugs, please post the submit *commands*, *error report logs* and related *code snippet* 
- For feature requests, please describe what's you scenario and why you need this feature

就贴这么一段日志很难看出是什么问题，这种无效的issue我这边先close了，麻烦按照基本格式重新提吧
