### ISSUE TITLE
angel在yarn上运行LR失败

### ISSUE THREAD

**Issue by zhaoyunyemu** [Angel-ML/angel#313]
提交命令：
        ./angel-submit \
 	--angel.app.submit.class "com.tencent.angel.ml.classification.lr.LRRunner"\
 	--angel.train.data.path "/user/hdfs/lr_data" \
 	--angel.log.path "/user/hdfs/log" \
 	--angel.save.model.path "/user/hdfs/model" \
 	--action.type train \
	--angel.am.env JAVA_HOME=/opt/jdk1.8.0_101 \
	--angel.worker.env JAVA_HOME=/opt/jdk1.8.0_101 \
	--ml.data.type libsvm \
 	--ml.feature.num 1024 \
 	--angel.job.name LR_test \
 	--angel.am.memory.gb 2 \
 	--angel.worker.memory.gb 2 \
 	--angel.ps.memory.gb 2
错误日志：
start to create rpc client to am
18/04/13 11:59:46 ERROR yarn.AngelYarnClient: submit application to yarn failed.
com.google.protobuf.ServiceException: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /10.159.59.53:24292
        at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:318)
        at com.sun.proxy.$Proxy14.getAllPSLocation(Unknown Source)
        at com.tencent.angel.client.AngelClient.waitForAllPS(AngelClient.java:811)
        at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:170)
        at com.tencent.angel.ml.MLRunner$class.train(MLRunner.scala:47)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:32)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:42)
        at com.tencent.angel.ml.MLRunner$class.submit(MLRunner.scala:93)
        at com.tencent.angel.ml.classification.lr.LRRunner.submit(LRRunner.scala:32)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:67)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:54)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
        at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:54)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:38)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /10.159.59.53:24292
        at com.tencent.angel.ipc.CallFuture.get(CallFuture.java:126)
        at com.tencent.angel.ipc.NettyTransceiver.call(NettyTransceiver.java:316)
        at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:295)
详细日志如下：
at org.apache.hadoop.util.Shell.run(Shell.java:478)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Container exited with a non-zero exit code 255

PSAttempt_0_1 failed due to: Java heap space
PSAttempt_0_2 failed due to: Java heap space
PSAttempt_0_3 failed due to: Java heap space

**Comment by paynie** [comment]
How large is your PS memory?

**Comment by paynie** [comment]
2G is too small， you can try a larger value
