### ISSUE TITLE
GDBT

### ISSUE THREAD

**Issue by lxl910915** [Angel-ML/angel#360]
起2个ps和2个worker，其中一个worker报错java.lang.ArrayIndexOutOfBoundsException: 0。
调试了一下发现报错的worker中没有拿到数据。RegLossObj的calGrad()方法中preds.length长度为0。

具体报错如下：
`2018-07-13 12:05:49,493 INFO [main] com.tencent.angel.worker.Worker: angel.cluster.local.dir for child: 
2018-07-13 12:05:49,494 INFO [main] com.tencent.angel.worker.Worker: actual workergroup number:4
2018-07-13 12:05:49,494 INFO [main] com.tencent.angel.worker.Worker: actual task number:4
2018-07-13 12:05:49,523 INFO [main] com.tencent.angel.worker.Worker: Init and start worker
2018-07-13 12:05:49,525 INFO [main] com.tencent.angel.worker.Worker: Init and start psagent for worker
2018-07-13 12:05:49,695 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2018-07-13 12:05:49,695 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2018-07-13 12:05:49,860 INFO [main] com.tencent.angel.psagent.PSAgent: PSAgent get matrices from master,136
2018-07-13 12:05:49,896 INFO [main] com.tencent.angel.psagent.matrix.transport.MatrixTransportClient: ByteOrder.nativeOrder()=LITTLE_ENDIAN
2018-07-13 12:05:49,900 INFO [main] com.tencent.angel.worker.Worker: Init data block manager
2018-07-13 12:05:49,900 INFO [main] com.tencent.angel.worker.Worker: Init and start worker rpc server
2018-07-13 12:05:49,921 INFO [main] com.tencent.angel.worker.WorkerService: Starting workerserver service at 10.210.64.119:30219
2018-07-13 12:05:49,921 INFO [main] com.tencent.angel.worker.Worker: Init counter updater
2018-07-13 12:05:49,955 INFO [main] com.tencent.angel.psagent.CounterUpdater:  Using ResourceCalculatorProcessTree : [ ]
2018-07-13 12:05:49,955 INFO [main] com.tencent.angel.worker.Worker: Register to master and start the heartbeat thread
2018-07-13 12:05:49,955 INFO [main] com.tencent.angel.worker.Worker: Get data splits from master
2018-07-13 12:05:49,955 INFO [Worker Heartbeat] com.tencent.angel.worker.Worker: WorkerAttempt_3_3_0 register to master
2018-07-13 12:05:49,963 ERROR [Worker Heartbeat] com.tencent.angel.worker.Worker: worker received shutdown command when register to master, to exit now!
2018-07-13 12:05:51,944 INFO [main] com.tencent.angel.worker.Worker: angel.cluster.local.dir for child: 
2018-07-13 12:05:51,945 INFO [main] com.tencent.angel.worker.Worker: actual workergroup number:4
2018-07-13 12:05:51,945 INFO [main] com.tencent.angel.worker.Worker: actual task number:4
2018-07-13 12:05:51,975 INFO [main] com.tencent.angel.worker.Worker: Init and start worker
2018-07-13 12:05:51,977 INFO [main] com.tencent.angel.worker.Worker: Init and start psagent for worker
2018-07-13 12:05:52,146 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2018-07-13 12:05:52,146 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2018-07-13 12:05:52,312 INFO [main] com.tencent.angel.psagent.PSAgent: PSAgent get matrices from master,136
2018-07-13 12:05:52,348 INFO [main] com.tencent.angel.psagent.matrix.transport.MatrixTransportClient: ByteOrder.nativeOrder()=LITTLE_ENDIAN
2018-07-13 12:05:52,354 INFO [main] com.tencent.angel.worker.Worker: Init data block manager
2018-07-13 12:05:52,354 INFO [main] com.tencent.angel.worker.Worker: Init and start worker rpc server
2018-07-13 12:05:52,375 INFO [main] com.tencent.angel.worker.WorkerService: Starting workerserver service at 10.210.64.119:31667
2018-07-13 12:05:52,375 INFO [main] com.tencent.angel.worker.Worker: Init counter updater
2018-07-13 12:05:52,388 INFO [main] com.tencent.angel.psagent.CounterUpdater:  Using ResourceCalculatorProcessTree : [ ]
2018-07-13 12:05:52,388 INFO [main] com.tencent.angel.worker.Worker: Register to master and start the heartbeat thread
2018-07-13 12:05:52,388 INFO [main] com.tencent.angel.worker.Worker: Get data splits from master
2018-07-13 12:05:52,388 INFO [Worker Heartbeat] com.tencent.angel.worker.Worker: WorkerAttempt_3_3_0 register to master
2018-07-13 12:05:52,395 INFO [Worker Heartbeat] com.tencent.angel.worker.Worker: WorkerAttempt_3_3_0 register to master finished!
2018-07-13 12:05:53,486 INFO [main] com.tencent.angel.worker.Worker: Init and start task manager and all task
2018-07-13 12:05:53,486 INFO [main] com.tencent.angel.worker.task.TaskManager: start all tasks
2018-07-13 12:05:53,487 INFO [main] com.tencent.angel.worker.task.TaskManager: start task task_3 with context=TaskContext [taskId=task_3, taskIdProto=taskIndex: 3
, context=com.tencent.angel.psagent.task.TaskContext@6e9a5ed8TaskContext [index=3, matrix clocks=]]
2018-07-13 12:05:53,488 INFO [pool-6-thread-1] com.tencent.angel.worker.task.Task: task task_3 is running.
2018-07-13 12:05:53,490 INFO [pool-6-thread-1] com.tencent.angel.worker.task.Task: userTaskClass = class com.tencent.angel.ml.GBDT.GBDTTrainTask task index = 3, name = Thread-18
2018-07-13 12:05:53,623 INFO [pool-6-thread-1] com.tencent.angel.ml.model.PSModel: After training matrix gbdt.split.feature will be saved to /data/project/qiezi/angel-gbdt/t1/model/
2018-07-13 12:05:53,623 INFO [pool-6-thread-1] com.tencent.angel.ml.model.PSModel: After training matrix gbdt.node.predict will be saved to /data/project/qiezi/angel-gbdt/t1/model/
2018-07-13 12:05:53,623 INFO [pool-6-thread-1] com.tencent.angel.ml.model.PSModel: After training matrix gbdt.split.value will be saved to /data/project/qiezi/angel-gbdt/t1/model/
2018-07-13 12:05:53,623 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: 1. initialize
2018-07-13 12:05:53,626 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Create data meta, numFeature=10000, nonzero=-1
2018-07-13 12:05:53,632 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Finish creating data meta, numRow=0, numCol=10000, nonzero=-1
2018-07-13 12:05:53,632 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Create data meta, numFeature=10000, nonzero=-1
2018-07-13 12:05:53,634 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Finish creating data meta, numRow=0, numCol=10000, nonzero=-1
2018-07-13 12:05:53,634 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Build data info cost 11 ms
2018-07-13 12:05:53,634 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: 2.train
2018-07-13 12:05:53,647 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: ******Current phase: CREATE_SKETCH, clock[0]******
2018-07-13 12:05:53,969 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: clock and flush matrices [gbdt.feature.category, gbdt.sketch] cost 321 ms
2018-07-13 12:05:53,969 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: ------Merge categorical features------
2018-07-13 12:05:54,192 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: clock and flush matrices [] cost 223 ms
2018-07-13 12:05:54,320 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: ******Current phase: GET_SKETCH, clock[1]******
2018-07-13 12:05:54,320 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: ------Get sketch from PS------
2018-07-13 12:05:54,321 INFO [pool-6-thread-1] com.tencent.angel.psagent.consistency.ConsistencyController: wait for clock 2
2018-07-13 12:06:12,384 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: Get sketch cost: 18064 ms
2018-07-13 12:06:12,389 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: Number of splits of categorical features: []
2018-07-13 12:06:12,389 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: ------Sample feature------
2018-07-13 12:06:12,598 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: clock and flush matrices [] cost 209 ms
2018-07-13 12:06:12,599 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: ******Current phase: NEW_TREE, clock[2]******
2018-07-13 12:06:12,599 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: ------Create new tree------
2018-07-13 12:06:12,601 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: ------Calculate grad pairs------
2018-07-13 12:06:12,601 ERROR [pool-6-thread-1] com.tencent.angel.worker.task.Task: task runner error 
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.tencent.angel.ml.GBDT.algo.GBDTController.calGradPairs(GBDTController.java:174)
	at com.tencent.angel.ml.GBDT.algo.GBDTController.createNewTree(GBDTController.java:388)
	at com.tencent.angel.ml.GBDT.GBDTLearner.train(GBDTLearner.scala:193)
	at com.tencent.angel.ml.GBDT.GBDTTrainTask.train(GBDTTrainTask.scala:47)
	at com.tencent.angel.ml.task.TrainTask.run(TrainTask.scala:29)
	at com.tencent.angel.worker.task.Task.runUserTask(Task.java:95)
	at com.tencent.angel.worker.task.Task.run(Task.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-07-13 12:06:12,615 INFO [pool-6-thread-1] com.tencent.angel.worker.Worker: worker failed message : taskid=task_3, state=FAILED, diagnostics=[task runner error: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.tencent.angel.ml.GBDT.algo.GBDTController.calGradPairs(GBDTController.java:174)
	at com.tencent.angel.ml.GBDT.algo.GBDTController.createNewTree(GBDTController.java:388)
	at com.tencent.angel.ml.GBDT.GBDTLearner.train(GBDTLearner.scala:193)
	at com.tencent.angel.ml.GBDT.GBDTTrainTask.train(GBDTTrainTask.scala:47)
	at com.tencent.angel.ml.task.TrainTask.run(TrainTask.scala:29)
	at com.tencent.angel.worker.task.Task.runUserTask(Task.java:95)
	at com.tencent.angel.worker.task.Task.run(Task.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
], send it to appmaster success
2018-07-13 12:06:12,615 INFO [pool-6-thread-1] com.tencent.angel.worker.Worker: start to close all modules in worker
2018-07-13 12:06:12,615 INFO [pool-6-thread-1] com.tencent.angel.worker.Worker: stop workerService
2018-07-13 12:06:12,616 INFO [pool-6-thread-1] com.tencent.angel.worker.WorkerService: stop rpc server
2018-07-13 12:06:12,616 INFO [pool-6-thread-1] com.tencent.angel.ipc.NettyServer: Stopping server on 31667
2018-07-13 12:06:12,628 INFO [pool-6-thread-1] com.tencent.angel.worker.Worker: stop psagent
2018-07-13 12:06:12,628 INFO [pool-6-thread-1] com.tencent.angel.psagent.PSAgent: stop heartbeat thread!
2018-07-13 12:06:12,628 INFO [pool-6-thread-1] com.tencent.angel.psagent.PSAgent: stop op log merger
2018-07-13 12:06:12,629 WARN [oplog-merge-dispatcher] com.tencent.angel.psagent.matrix.oplog.cache.MatrixOpLogCache: oplog-merge-dispatcher interrupted
2018-07-13 12:06:12,630 INFO [pool-6-thread-1] com.tencent.angel.psagent.PSAgent: stop clock cache
2018-07-13 12:06:12,631 INFO [pool-6-thread-1] com.tencent.angel.psagent.PSAgent: stop matrix cache
2018-07-13 12:06:12,631 INFO [clock-syncer] com.tencent.angel.psagent.clock.ClockCache: sync thread is interrupted
2018-07-13 12:06:12,631 INFO [pool-6-thread-1] com.tencent.angel.psagent.PSAgent: stop matrix client adapater
2018-07-13 12:06:12,631 INFO [pool-6-thread-1] com.tencent.angel.psagent.PSAgent: stop rpc dispacher
2018-07-13 12:06:12,631 INFO [row-merge-dispatcher] com.tencent.angel.psagent.matrix.transport.adapter.MatrixClientAdapter: MergeDispatcher is interrupted
2018-07-13 12:06:12,646 INFO [pool-6-thread-1] com.tencent.angel.worker.Worker: stop heartbeat thread
2018-07-13 12:06:12,646 INFO [pool-6-thread-1] com.tencent.angel.worker.Worker: stop task manager
2018-07-13 12:06:12,646 INFO [pool-6-thread-1] com.tencent.angel.worker.Worker: stop data block manager
2018-07-13 12:08:31,586 INFO [main] com.tencent.angel.worker.Worker: angel.cluster.local.dir for child: 
2018-07-13 12:08:31,588 INFO [main] com.tencent.angel.worker.Worker: actual workergroup number:4
2018-07-13 12:08:31,588 INFO [main] com.tencent.angel.worker.Worker: actual task number:4
2018-07-13 12:08:31,616 INFO [main] com.tencent.angel.worker.Worker: Init and start worker
2018-07-13 12:08:31,618 INFO [main] com.tencent.angel.worker.Worker: Init and start psagent for worker
2018-07-13 12:08:31,792 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2018-07-13 12:08:31,792 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2018-07-13 12:08:31,960 INFO [main] com.tencent.angel.psagent.PSAgent: PSAgent get matrices from master,136
2018-07-13 12:08:31,996 INFO [main] com.tencent.angel.psagent.matrix.transport.MatrixTransportClient: ByteOrder.nativeOrder()=LITTLE_ENDIAN
2018-07-13 12:08:32,000 INFO [main] com.tencent.angel.worker.Worker: Init data block manager
2018-07-13 12:08:32,000 INFO [main] com.tencent.angel.worker.Worker: Init and start worker rpc server
2018-07-13 12:08:32,021 INFO [main] com.tencent.angel.worker.WorkerService: Starting workerserver service at 10.210.64.65:31623
2018-07-13 12:08:32,021 INFO [main] com.tencent.angel.worker.Worker: Init counter updater
2018-07-13 12:08:32,034 INFO [main] com.tencent.angel.psagent.CounterUpdater:  Using ResourceCalculatorProcessTree : [ ]
2018-07-13 12:08:32,034 INFO [main] com.tencent.angel.worker.Worker: Register to master and start the heartbeat thread
2018-07-13 12:08:32,034 INFO [main] com.tencent.angel.worker.Worker: Get data splits from master
2018-07-13 12:08:32,034 INFO [Worker Heartbeat] com.tencent.angel.worker.Worker: WorkerAttempt_3_3_0 register to master
2018-07-13 12:08:32,051 ERROR [Worker Heartbeat] com.tencent.angel.worker.Worker: worker received shutdown command when register to master, to exit now!
2018-07-13 12:08:33,755 INFO [main] com.tencent.angel.worker.Worker: angel.cluster.local.dir for child: 
2018-07-13 12:08:33,757 INFO [main] com.tencent.angel.worker.Worker: actual workergroup number:4
2018-07-13 12:08:33,757 INFO [main] com.tencent.angel.worker.Worker: actual task number:4
2018-07-13 12:08:33,786 INFO [main] com.tencent.angel.worker.Worker: Init and start worker
2018-07-13 12:08:33,788 INFO [main] com.tencent.angel.worker.Worker: Init and start psagent for worker
2018-07-13 12:08:33,958 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2018-07-13 12:08:33,959 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2018-07-13 12:08:34,124 INFO [main] com.tencent.angel.psagent.PSAgent: PSAgent get matrices from master,136
2018-07-13 12:08:34,160 INFO [main] com.tencent.angel.psagent.matrix.transport.MatrixTransportClient: ByteOrder.nativeOrder()=LITTLE_ENDIAN
2018-07-13 12:08:34,164 INFO [main] com.tencent.angel.worker.Worker: Init data block manager
2018-07-13 12:08:34,164 INFO [main] com.tencent.angel.worker.Worker: Init and start worker rpc server
2018-07-13 12:08:34,185 INFO [main] com.tencent.angel.worker.WorkerService: Starting workerserver service at 10.210.64.65:31881
2018-07-13 12:08:34,185 INFO [main] com.tencent.angel.worker.Worker: Init counter updater
2018-07-13 12:08:34,199 INFO [main] com.tencent.angel.psagent.CounterUpdater:  Using ResourceCalculatorProcessTree : [ ]
2018-07-13 12:08:34,199 INFO [main] com.tencent.angel.worker.Worker: Register to master and start the heartbeat thread
2018-07-13 12:08:34,199 INFO [main] com.tencent.angel.worker.Worker: Get data splits from master
2018-07-13 12:08:34,199 INFO [Worker Heartbeat] com.tencent.angel.worker.Worker: WorkerAttempt_3_3_0 register to master
2018-07-13 12:08:34,206 ERROR [Worker Heartbeat] com.tencent.angel.worker.Worker: worker received shutdown command when register to master, to exit now!
2018-07-13 12:08:52,140 INFO [main] com.tencent.angel.worker.Worker: angel.cluster.local.dir for child: 
2018-07-13 12:08:52,142 INFO [main] com.tencent.angel.worker.Worker: actual workergroup number:4
2018-07-13 12:08:52,142 INFO [main] com.tencent.angel.worker.Worker: actual task number:4
2018-07-13 12:08:52,170 INFO [main] com.tencent.angel.worker.Worker: Init and start worker
2018-07-13 12:08:52,172 INFO [main] com.tencent.angel.worker.Worker: Init and start psagent for worker
2018-07-13 12:08:52,338 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2018-07-13 12:08:52,339 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2018-07-13 12:08:52,500 INFO [main] com.tencent.angel.psagent.PSAgent: PSAgent get matrices from master,136
2018-07-13 12:08:52,536 INFO [main] com.tencent.angel.psagent.matrix.transport.MatrixTransportClient: ByteOrder.nativeOrder()=LITTLE_ENDIAN
2018-07-13 12:08:52,540 INFO [main] com.tencent.angel.worker.Worker: Init data block manager
2018-07-13 12:08:52,540 INFO [main] com.tencent.angel.worker.Worker: Init and start worker rpc server
2018-07-13 12:08:52,566 INFO [main] com.tencent.angel.worker.WorkerService: Starting workerserver service at 10.210.64.65:30223
2018-07-13 12:08:52,567 INFO [main] com.tencent.angel.worker.Worker: Init counter updater
2018-07-13 12:08:52,580 INFO [main] com.tencent.angel.psagent.CounterUpdater:  Using ResourceCalculatorProcessTree : [ ]
2018-07-13 12:08:52,580 INFO [main] com.tencent.angel.worker.Worker: Register to master and start the heartbeat thread
2018-07-13 12:08:52,580 INFO [main] com.tencent.angel.worker.Worker: Get data splits from master
2018-07-13 12:08:52,581 INFO [Worker Heartbeat] com.tencent.angel.worker.Worker: WorkerAttempt_3_3_0 register to master
2018-07-13 12:08:52,587 INFO [Worker Heartbeat] com.tencent.angel.worker.Worker: WorkerAttempt_3_3_0 register to master finished!
2018-07-13 12:08:53,659 INFO [main] com.tencent.angel.worker.Worker: Init and start task manager and all task
2018-07-13 12:08:53,659 INFO [main] com.tencent.angel.worker.task.TaskManager: start all tasks
2018-07-13 12:08:53,659 INFO [main] com.tencent.angel.worker.task.TaskManager: start task task_3 with context=TaskContext [taskId=task_3, taskIdProto=taskIndex: 3
, context=com.tencent.angel.psagent.task.TaskContext@5b247367TaskContext [index=3, matrix clocks=]]
2018-07-13 12:08:53,661 INFO [pool-6-thread-1] com.tencent.angel.worker.task.Task: task task_3 is running.
2018-07-13 12:08:53,663 INFO [pool-6-thread-1] com.tencent.angel.worker.task.Task: userTaskClass = class com.tencent.angel.ml.GBDT.GBDTTrainTask task index = 3, name = Thread-18
2018-07-13 12:08:53,798 INFO [pool-6-thread-1] com.tencent.angel.ml.model.PSModel: After training matrix gbdt.split.feature will be saved to /data/project/qiezi/angel-gbdt/t1/model/
2018-07-13 12:08:53,798 INFO [pool-6-thread-1] com.tencent.angel.ml.model.PSModel: After training matrix gbdt.node.predict will be saved to /data/project/qiezi/angel-gbdt/t1/model/
2018-07-13 12:08:53,798 INFO [pool-6-thread-1] com.tencent.angel.ml.model.PSModel: After training matrix gbdt.split.value will be saved to /data/project/qiezi/angel-gbdt/t1/model/
2018-07-13 12:08:53,798 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: 1. initialize
2018-07-13 12:08:53,802 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Create data meta, numFeature=10000, nonzero=-1
2018-07-13 12:08:53,807 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Finish creating data meta, numRow=0, numCol=10000, nonzero=-1
2018-07-13 12:08:53,807 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Create data meta, numFeature=10000, nonzero=-1
2018-07-13 12:08:53,810 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Finish creating data meta, numRow=0, numCol=10000, nonzero=-1
2018-07-13 12:08:53,810 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: Build data info cost 12 ms
2018-07-13 12:08:53,810 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: 2.train
2018-07-13 12:08:53,822 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: ******Current phase: CREATE_SKETCH, clock[0]******
2018-07-13 12:08:54,167 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: clock and flush matrices [gbdt.feature.category, gbdt.sketch] cost 344 ms
2018-07-13 12:08:54,167 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: ------Merge categorical features------
2018-07-13 12:08:54,383 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: clock and flush matrices [] cost 216 ms
2018-07-13 12:08:54,448 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.GBDTLearner: ******Current phase: GET_SKETCH, clock[1]******
2018-07-13 12:08:54,448 INFO [pool-6-thread-1] com.tencent.angel.ml.GBDT.algo.GBDTController: ------Get sketch from PS------
2018-07-13 12:08:54,448 INFO [pool-6-thread-1] com.tencent.angel.psagent.consistency.ConsistencyController: wait for clock 2
`

**Comment by lxl910915** [comment]
开始在训练数据目录下只放了agaricus.txt.test，又存放了agaricus.txt.train，可以正常训练了。请问*.test 和 *.train是必须同时放吗？ 命名有要求吗？

**Comment by bluesjjw** [comment]
测试代码中，agaricus.txt.test和agaricus.txt.train要都存在。

自己配置的任务，可以指定训练数据目录。

**Comment by lxl910915** [comment]
@bluesjjw 自己配置的任务，指定训练数据目录时是否可以只存在一个数据集？上述报错是自己配置的任务，数据目录下只放了agaricus.txt.train数据。

**Comment by bluesjjw** [comment]
可以只存在一个数据集的，您现在还有这个问题？

**Comment by wwwyyy** [comment]
我也碰到了类似的问题,在lr on yarn上 设置多个woker 或者在一个woker下设置多个task会出现java.lang.ArrayIndexOutOfBoundsException: 0
我的submit
./angel-submit \
--angel.deploy.mode YARN \
--angel.app.submit.class "com.tencent.angel.ml.classification.lr.LRRunner" \
--angel.train.data.path "hdfs:///user/zengxy/1000_68.txt" \
--angel.log.path "file:///var/log/angel/t7" \
--angel.save.model.path "hdfs:///user/zengxy/angeltest/lr_model/1wmodel19" \
--angel.am.env JAVA_HOME=/usr/java/jdk1.8.0_25 \
--angel.worker.env JAVA_HOME=/usr/java/jdk1.8.0_25 \
--angel.ps.env JAVA_HOME=/usr/java/jdk1.8.0_25 \
--action.type train \
--ml.epoch.num 5 \
--ml.data.type libsvm \
--ml.feature.index.range 1000 \
--angel.job.name angel_GDLR_1m \
--angel.workergroup.number 2 \
--angel.worker.task.number 4 \
--angel.worker.cpu.vcores 8 \
--angel.worker.memory.gb 16 \
--angel.ps.number 4 \
--angel.ps.cpu.vcores 2 \
--angel.ps.memory.gb 4 \
--angel.am.memory.gb 4 \
~                           
请问你们是如何解决的呀?

**Comment by lxl910915** [comment]
@wwwyyy  1个worker 1个ps试下可不可以运行呢？

**Comment by lxl910915** [comment]
要求数据文件的个数大于worker个数
