### ISSUE TITLE
FM nio network error

### ISSUE THREAD

**Issue by wuciawe** [Angel-ML/angel#361]
When I run the FM, I meet the following error. How to tune the parameter to avoid this?

```
2018-07-16 20:05:22,983 ERROR [nioEventLoopGroup-5-61] com.tencent.angel.ps.matrix.transport.WorkerPool: send response of request clientId=29/seqId=2523 failed 
2018-07-16 20:05:22,983 ERROR [nioEventLoopGroup-5-61] com.tencent.angel.ps.matrix.transport.WorkerPool: send response of request clientId=29/seqId=2629 failed 
2018-07-16 20:05:32,774 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 3 token is timeout
2018-07-16 20:05:32,774 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 20 token is timeout
2018-07-16 20:05:32,774 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 29 token is timeout
2018-07-16 20:05:32,774 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 35 token is timeout
2018-07-16 20:05:37,774 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 12 token is timeout
2018-07-16 20:05:42,775 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 37 token is timeout
2018-07-16 20:05:47,775 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 29 token is timeout
2018-07-16 20:05:52,775 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 22 token is timeout
2018-07-16 20:05:52,775 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 35 token is timeout
2018-07-16 20:05:57,776 INFO [token-timeout-checker] com.tencent.angel.ps.impl.RunningContext: client 30 token is timeout
2018-07-16 20:05:58,289 ERROR [nioEventLoopGroup-5-57] com.tencent.angel.ps.matrix.transport.MatrixTransportServerHandler: catch a exception 
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by paynie** [comment]
Maybe you need adjust the PS memory

**Comment by wuciawe** [comment]
@paynie do you mean increase `angel.ps.memory.gb`?

**Comment by paynie** [comment]
Yes， you can try
