### ISSUE TITLE
Quickstart QLRRunner load submit class failed

### ISSUE THREAD

**Issue by gdamaskinos** [Angel-ML/angel#371]
I followed the instructions mentioned [here](https://github.com/Tencent/angel/blob/master/docs/deploy/run_on_yarn_en.md) and I get:

```bash
$ ./angel-submit         --angel.app.submit.class com.tencent.angel.example.quickstart.QSLRRunner        --angel.train.data.path "hdfs:///test/lr_data"         --angel.log.path "hdfs:///test/log"         --angel.save.model.path "hdfs:///test/model"         --action.type train         --ml.data.type dummy         --ml.feature.num 1024         --angel.job.name LR_test         --angel.am.memory.gb 2         --angel.worker.memory.gb 2         --angel.ps.memory.gb 2
WARNING: DEFAULT_LIBEXEC_DIR ignored. It has been replaced by HADOOP_DEFAULT_LIBEXEC_DIR.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/gdamaskinos/hadoop-3.1.0/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/lib/slf4j-log4j12-1.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2018-08-04 13:41:00,511 INFO utils.AngelRunJar: angelHomePath conf path=/home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//conf/angel-site.xml
2018-08-04 13:41:00,512 INFO utils.AngelRunJar: load system config file success
2018-08-04 13:41:00,539 INFO utils.AngelRunJar: jars loaded: file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/angel-ps-serving-1.5.1.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/netty-all-4.1.1.Final.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/angel-ps-mllib-1.5.1.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/angel-ps-tools-1.5.1.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/scala-reflect-2.11.7.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/memory-0.8.1.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/sketches-core-0.8.1.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/commons-pool-1.6.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/kryo-shaded-4.0.0.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/kryo-serializers-0.42.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/scala-library-2.11.8.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/angel-ps-core-1.5.1.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/angel-ps-psf-1.5.1.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/angel-ps-examples-1.5.1.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/fastutil-7.1.0.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/sizeof-0.3.0.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/minlog-1.3.0.jar,file:///home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/breeze_2.11-0.12.jar
2018-08-04 13:41:00,539 INFO utils.AngelRunJar: angel python file: null
2018-08-04 13:41:00,555 INFO utils.UGITools: UGI_PROPERTY_NAME is null
2018-08-04 13:41:00,557 FATAL utils.AngelRunJar: load submit class failed com.tencent.angel.example.quickstart.QSLRRunner
java.lang.ClassNotFoundException: com.tencent.angel.example.quickstart.QSLRRunner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:58)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:54)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:54)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:38)
2018-08-04 13:41:00,559 FATAL utils.AngelRunJar: submit job failed
java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1700)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:54)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:38)
Caused by: com.tencent.angel.exception.InvalidParameterException: load submit class failed com.tencent.angel.example.quickstart.QSLRRunner
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:64)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:54)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
	... 2 more
```

The jar that contains the required class seems to be loaded:

```bash
$ jar tf /home/gdamaskinos/angel/dist/target/angel-1.5.1-bin/bin/..//lib/angel-ps-examples-1.5.1.jar | grep -i QSLRRunner
com/tencent/angel/example/quickStart/QSLRRunner.class
```

Am I missing something?

Thank you in advance.

**Comment by yang3808282** [comment]
I also meet that question，how do you fix it ，can you tell me ,thanks

**Comment by Brentbin** [comment]
same question and not answer but closed?
@paynie
