### ISSUE TITLE
FM Predict Error

### ISSUE THREAD

**Issue by lakezhang** [Angel-ML/angel#373]
sh /home/work/work/spark/angel-1.4.0-bin/bin/angel-submit --angel.app.submit.class com.tencent.angel.ml.factorizationmachines.FMRunner --angel.predict.data.path hdfs:///user/feature/sign_2018-07-27_1_8/ --angel.predict.out.path hdfs:///user/feature/sign_2018-07-27_1_8_predict_5 --angel.log.path hdfs:///user/feature/logs/p_5 --angel.load.model.path hdfs:///user/model/lr_5 --action.type predict --ml.data.type libsvm --ml.feature.num 8033 --angel.job.name LR_test --angel.am.memory.gb 20 --angel.worker.memory.gb 10 --angel.ps.memory.gb 20 --angel.workergroup.number 100 --angel.worker.cpu.vcores 2

ERROR：

18/08/07 10:26:34 INFO utils.AngelRunJar: submitClass: com.tencent.angel.ml.factorizationmachines.FMRunner
Exception in thread "main" scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)
	at com.tencent.angel.ml.factorizationmachines.FMRunner.predict(FMRunner.scala:43)
	at com.tencent.angel.ml.MLRunner$class.submit(MLRunner.scala:97)
	at com.tencent.angel.ml.factorizationmachines.FMRunner.submit(FMRunner.scala:26)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:67)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:54)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:54)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:38)

**Comment by csbwang** [comment]
你好，你有尝试过将模型导出吗，我看产出的模型是二进制文件，这个无法解析自用啊
