### ISSUE TITLE
Spark on angel : java.lang.AbstractMethodError: com.tencent.angel.spark.models.vector.enhanced.BreezePSVector

### ISSUE THREAD

**Issue by wwwyyy** [Angel-ML/angel#396]
在跑 sparseLRwithLBFGS OWLQN都会出现这个错误(可以正常迭代几轮出来然后报错),请问这是为什么呀? (数据的问题吗?但是相同的数据,sparseLRwithSGD可以正常跑)数据是onehot随机的数据
Exception in thread "main" java.lang.AbstractMethodError: com.tencent.angel.spark.models.vector.enhanced.BreezePSVector.$minus$colon$minus(Ljava/lang/Object;Lbreeze/generic/UFunc$UImpl2;)Ljava/lang/Object;
	at breeze.optimize.LBFGS.updateHistory(LBFGS.scala:57)
	at breeze.optimize.LBFGS.updateHistory(LBFGS.scala:39)
	at breeze.optimize.FirstOrderMinimizer$$anonfun$infiniteIterations$1.apply(FirstOrderMinimizer.scala:71)
	at breeze.optimize.FirstOrderMinimizer$$anonfun$infiniteIterations$1.apply(FirstOrderMinimizer.scala:62)
	at scala.collection.Iterator$$anon$7.next(Iterator.scala:129)
	at breeze.util.IteratorImplicits$RichIterator$$anon$2.next(Implicits.scala:71)
	at com.tencent.angel.spark.ml.benchmark.SparseLRWithOWLQN$.runSparsePSOWLQN(SparseLRWithOWLQN.scala:147)
	at com.tencent.angel.spark.ml.benchmark.SparseLRWithOWLQN$.main(SparseLRWithOWLQN.scala:74)
	at com.tencent.angel.spark.ml.benchmark.SparseLRWithOWLQN.main(SparseLRWithOWLQN.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:795)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:182)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:207)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

命令:
./spark-shell 
--master yarn-client 
--conf spark.ps.jars=$SONA_ANGEL_JARS 
--conf spark.ps.instances=2 
--conf spark.ps.cores=4 
--conf spark.ps.memory=8g  
--conf spark.executorEnv.JAVA_HOME=/usr/java/jdk1.8.0_25 
 --conf spark.yarn.appMasterEnv.JAVA_HOME=/usr/java/jdk1.8.0_25 
--queue default --jars $SONA_SPARK_JARS 
--name "sparkonangeltest_lr" 
--driver-memory 8g 
--num-executors 4 
--executor-cores 1 
--executor-memory 8g 
--class com.tencent.angel.spark.ml.benchmark.SparseLRWithSGD 
 ./../lib/spark-on-angel-mllib-${ANGEL_VERSION}.jar input:hdfs:///user/zengxy/OneHotData/1000_100_OneHot.txt updateType:ps maxIter:20 mode:yarn-client

**Comment by paynie** [comment]
The angel version you use is ? @weiwee
