### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by douglasren** [Angel-ML/angel#397]
spark: 2.1.0   java:1.8   scala:2.11  

Job aborted due to stage failure: Task 8 in stage 5.0 failed 4 times, most recent failure: Lost task 8.3 in stage 5.0 (TID 43, c1-dsj-hadoop046.bj, executor 7): java.lang.UnsupportedOperationException
	at it.unimi.dsi.fastutil.ints.AbstractInt2DoubleMap$BasicEntry.setValue(AbstractInt2DoubleMap.java:146)
	at com.tencent.angel.ml.math2.ufuncs.executor.simple.SimpleUnaryExecutor.apply(SimpleUnaryExecutor.java:69)
	at com.tencent.angel.ml.math2.ufuncs.executor.simple.SimpleUnaryExecutor.apply(SimpleUnaryExecutor.java:32)
	at com.tencent.angel.ml.math2.ufuncs.executor.UnaryExecutor.apply(UnaryExecutor.java:33)
	at com.tencent.angel.ml.math2.vector.Vector.mul(Vector.java:136)
	at com.tencent.angel.ml.math2.matrix.RowBasedMatrix.transDot(RowBasedMatrix.java:121)
	at com.tencent.angel.ml.core.network.layers.edge.inputlayer.SparseInputLayer$$anonfun$pushGradient$1.apply$mcVI$sp(SparseInputLayer.scala:139)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.tencent.angel.ml.core.network.layers.edge.inputlayer.SparseInputLayer.pushGradient(SparseInputLayer.scala:136)
	at com.tencent.angel.ml.core.network.layers.AngelGraph$$anonfun$pushGradient$1.apply(AngelGraph.scala:150)
	at com.tencent.angel.ml.core.network.layers.AngelGraph$$anonfun$pushGradient$1.apply(AngelGraph.scala:150)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at com.tencent.angel.ml.core.network.layers.AngelGraph.pushGradient(AngelGraph.scala:150)
	at com.tencent.angel.spark.ml.core.GraphModel.backward(GraphModel.scala:72)
	at com.tencent.angel.spark.ml.core.OfflineLearner$$anonfun$train$1$$anonfun$2.apply(OfflineLearner.scala:84)
	at com.tencent.angel.spark.ml.core.OfflineLearner$$anonfun$train$1$$anonfun$2.apply(OfflineLearner.scala:79)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by paynie** [comment]
This problem looks like there are different versions of the fastutil package. You can check environment

**Comment by douglasren** [comment]
This is the reason for the fastutil package conflict
It can be solved in the following ways：
add conf "spark.executor.userClassPathFirst=true"
