### ISSUE TITLE
Shared Conf Dead Lock Caused worker blocked

### ISSUE THREAD

**Issue by Suanec** [Angel-ML/angel#400]
Angel - 2.0.0
FM algorithm thread deadlocked by eachother while worker has more than one task

when I submit a FM train job, as follow :
```shell
ANGEL_HOME=angel-2.0.0-alpha-bin
featureNum=10000000
validRatio=0.001
input_path=${LIBSVM_PATH}/libsvm_COPYMerged
suffix=$(date +_%Y%m%d_%s)
model_base_path=/user/fw/suanec/angel/models
model_path=${model_base_path}/fm_model$suffix
log_base_path=/user/fw/suanec/angel/logs
log_path=${log_base_path}/fm_model$suffix
workerNum=149
workerMem=80000
psNum=40
psMem=40000

./${ANGEL_HOME}/bin/angel-submit \
-Dml.epoch.num=1 \
-Dangel.app.submit.class=com.tencent.angel.ml.core.graphsubmit.GraphRunner \
-Dml.model.class.name=com.tencent.angel.ml.classification.FactorizationMachines \
-Dml.feature.index.range=$featureNum \
-Dml.feature.num=$featureNum \
-Dml.data.validate.ratio=$validRatio \
-Dml.data.type=libsvm \
-Dml.learn.rate=0.1 \
-Dml.learn.decay=0.5 \
-Dml.reg.l2=0.03 \
-Daction.type=train \
-Dml.fm.field.num=1 \
-Dml.fm.rank=100 \
-Dml.sparseinputlayer.optimizer=ftrl \
-Dangel.train.data.path=$input_path \
-Dangel.save.model.path=$model_path \
-Dangel.workergroup.number=$workerNum \
-Dangel.worker.memory.mb=$workerMem \
-Dangel.worker.task.number=2 \
-Dml.data.validate.ratio=0.000006 \
-Dstaleness=-1 \
-Dangel.worker.log.level=INFO \
-Dangel.ps.number=$psNum \
-Dangel.ps.memory.mb=$psMem \
-Dangel.task.data.storage.level=memory_disk \
-Dangel.job.name=fm_pressure_train
```
I found some unexpected action in yarn's web-UI.

some worker not start work while others start "KVDiskStorage create a new file" step.

when Elapsed cost 14 hours the situation not changed.

Then I found some usage information as follow which inspires me that may has threads fell into deadlocked.

```shell

"pool-5-thread-2" Id=676 RUNNABLE
	at scala.collection.mutable.HashTable$class.scala$collection$mutable$HashTable$$findEntry0(HashTable.scala:136)
	at scala.collection.mutable.HashTable$class.findOrAddEntry(HashTable.scala:165)
	at scala.collection.mutable.HashMap.findOrAddEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.put(HashMap.scala:76)
	at scala.collection.mutable.HashMap.update(HashMap.scala:81)
	at com.tencent.angel.ml.core.conf.SharedConf.update(SharedConf.scala:45)
	at com.tencent.angel.ml.core.conf.SharedConf$$anonfun$addMLConf$1.apply(SharedConf.scala:264)
	at com.tencent.angel.ml.core.conf.SharedConf$$anonfun$addMLConf$1.apply(SharedConf.scala:258)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.tencent.angel.ml.core.conf.SharedConf$.addMLConf(SharedConf.scala:258)
	at com.tencent.angel.ml.core.conf.SharedConf$.get(SharedConf.scala:243)
	at com.tencent.angel.ml.core.conf.SharedConf$.get(SharedConf.scala:251)
	at com.tencent.angel.ml.core.TrainTask.<init>(TrainTask.scala:40)
	at com.tencent.angel.ml.core.graphsubmit.GraphTrainTask.<init>(GraphTrainTask.scala:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.tencent.angel.worker.task.Task.newBaseTask(Task.java:83)
	at com.tencent.angel.worker.task.Task.run(Task.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@21129f1f



"pool-5-thread-1" Id=674 RUNNABLE
	at scala.collection.mutable.HashTable$class.scala$collection$mutable$HashTable$$findEntry0(HashTable.scala:136)
	at scala.collection.mutable.HashTable$class.findOrAddEntry(HashTable.scala:165)
	at scala.collection.mutable.HashMap.findOrAddEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.put(HashMap.scala:76)
	at scala.collection.mutable.HashMap.update(HashMap.scala:81)
	at com.tencent.angel.ml.core.conf.SharedConf.update(SharedConf.scala:45)
	at com.tencent.angel.ml.core.conf.SharedConf$$anonfun$addMLConf$1.apply(SharedConf.scala:264)
	at com.tencent.angel.ml.core.conf.SharedConf$$anonfun$addMLConf$1.apply(SharedConf.scala:258)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.tencent.angel.ml.core.conf.SharedConf$.addMLConf(SharedConf.scala:258)
	at com.tencent.angel.ml.core.conf.SharedConf$.get(SharedConf.scala:243)
	at com.tencent.angel.ml.core.conf.SharedConf$.get(SharedConf.scala:251)
	at com.tencent.angel.ml.core.TrainTask.<init>(TrainTask.scala:40)
	at com.tencent.angel.ml.core.graphsubmit.GraphTrainTask.<init>(GraphTrainTask.scala:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.tencent.angel.worker.task.Task.newBaseTask(Task.java:83)
	at com.tencent.angel.worker.task.Task.run(Task.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@6853425f
```

some blocked worker all log as follow :

```shell
worker -1 log：
2018-09-06 14:29:27,729 INFO [Worker Heartbeat] com.tencent.angel.worker.Worker: worker register finished!
2018-09-06 14:29:28,915 INFO [main] com.tencent.angel.worker.Worker: Init and start task manager and all task
2018-09-06 14:29:28,915 INFO [main] com.tencent.angel.worker.task.TaskManager: start all tasks
2018-09-06 14:29:28,915 INFO [main] com.tencent.angel.worker.task.TaskManager: start task task_36 with context=TaskContext [taskId=task_36, taskIdProto=taskIndex: 36
, context=com.tencent.angel.psagent.task.TaskContext@9573584TaskContext [index=36, matrix clocks=]]
2018-09-06 14:29:28,916 INFO [main] com.tencent.angel.worker.task.TaskManager: start task task_37 with context=TaskContext [taskId=task_37, taskIdProto=taskIndex: 37
, context=com.tencent.angel.psagent.task.TaskContext@352c1b98TaskContext [index=37, matrix clocks=]]
2018-09-06 14:29:28,916 INFO [pool-5-thread-1] com.tencent.angel.worker.task.Task: task task_36 is running.
2018-09-06 14:29:28,917 INFO [pool-5-thread-2] com.tencent.angel.worker.task.Task: task task_37 is running.
2018-09-06 14:29:28,928 INFO [pool-5-thread-1] com.tencent.angel.worker.task.Task: userTaskClass = class com.tencent.angel.ml.core.graphsubmit.GraphTrainTask task index = 36, name = Thread-574
2018-09-06 14:29:28,928 INFO [pool-5-thread-2] com.tencent.angel.worker.task.Task: userTaskClass = class com.tencent.angel.ml.core.graphsubmit.GraphTrainTask task index = 37, name = Thread-575

worker-2 log：
2018-09-06 14:29:28,336 INFO [pool-5-thread-2] com.tencent.angel.ml.core.conf.SharedConf: validate.loss does not have default value!
2018-09-06 14:29:28,336 INFO [pool-5-thread-1] com.tencent.angel.ml.core.conf.SharedConf: validate.loss does not have default value!
2018-09-06 14:29:28,336 INFO [pool-5-thread-1] com.tencent.angel.ml.core.conf.SharedConf: train.loss does not have default value!
2018-09-06 14:29:28,336 INFO [pool-5-thread-2] com.tencent.angel.ml.core.conf.SharedConf: train.loss does not have default value!
```

so I guess there are multithreads update SharedConf as same time, so that scala.collection.mutable.HashMap pending and wait others' operation。

config can't init successfully made worker pending and block all train job.

Then, I change parameter -Dangel.worker.task.number in my submit script. the status not reproduced.

modified script as follow :
```shell
ANGEL_HOME=angel-2.0.0-alpha-bin
featureNum=10000000
validRatio=0.001
input_path=${LIBSVM_PATH}/libsvm_COPYMerged
suffix=$(date +_%Y%m%d_%s)
model_base_path=/user/fw/suanec/angel/models
model_path=${model_base_path}/fm_model$suffix
log_base_path=/user/fw/suanec/angel/logs
log_path=${log_base_path}/fm_model$suffix
workerNum=149
workerMem=80000
psNum=40
psMem=40000

./${ANGEL_HOME}/bin/angel-submit \
-Dml.epoch.num=1 \
-Dangel.app.submit.class=com.tencent.angel.ml.core.graphsubmit.GraphRunner \
-Dml.model.class.name=com.tencent.angel.ml.classification.FactorizationMachines \
-Dml.feature.index.range=$featureNum \
-Dml.feature.num=$featureNum \
-Dml.data.validate.ratio=$validRatio \
-Dml.data.type=libsvm \
-Dml.learn.rate=0.1 \
-Dml.learn.decay=0.5 \
-Dml.reg.l2=0.03 \
-Daction.type=train \
-Dml.fm.field.num=1 \
-Dml.fm.rank=100 \
-Dml.sparseinputlayer.optimizer=ftrl \
-Dangel.train.data.path=$input_path \
-Dangel.save.model.path=$model_path \
-Dangel.workergroup.number=$workerNum \
-Dangel.worker.memory.mb=$workerMem \
-Dangel.worker.task.number=1 \
-Dml.data.validate.ratio=0.000006 \
-Dstaleness=-1 \
-Dangel.worker.log.level=INFO \
-Dangel.ps.number=$psNum \
-Dangel.ps.memory.mb=$psMem \
-Dangel.task.data.storage.level=memory_disk \
-Dangel.job.name=fm_pressure_train

```

Thanks for No.1 Angel-service to confirm this question.

**Comment by leleyu** [comment]
This problem is fixed by adding synchronized to the get() function of SharedConf
