### ISSUE TITLE
Release-2.0.0-alpha版本LDA运行内存溢出

### ISSUE THREAD

**Issue by gaoxjin** [Angel-ML/angel#411]
./angel-submit \\
--action.type train \\
--angel.deploy.mode LOCAL \\
--angel.app.submit.class com.tencent.angel.ml.lda.LDARunner \\
--angel.train.data.path "hdfs://192.168.2.21:9000/docx/docx.txt" \\
--angel.save.model.path "hdfs://192.168.2.21:9000/output/" \\
--angel.log.path "hdfs://192.168.2.21:9000/output/log" \\
--save.doc.topic true \\
--save.word.topic true \\
--ml.epoch.num 2 \\
--ml.lda.word.num 230342 \\
--ml.lda.topic.num 100 \\
--ml.lda.alpha 1 \\
--ml.lda.beta 1 \\
--ml.worker.thread.num ８ \\
--angel.am.memory.gb 8 \\
--angel.worker.memory.gb 16 \\
--angel.ps.memory.gb 16 \\
--angel.am.java.opts "-Xms8g -Xmx8g" \\
--angel.worker.java.opts "-Xms16g -Xmx16g" \\
--angel.ps.java.opts "-Xms16g -Xmx16g"

2018-09-20 15:22:50,671 INFO partitioner.RangePartitioner: blockRow = 1, blockCol=100
2018-09-20 15:22:50,671 INFO partitioner.RangePartitioner: partition count: 1
2018-09-20 15:22:56,005 INFO matrix.ServerMatrix: Creating a Server Matrix, id: 0, name: vocabulary
2018-09-20 15:23:18,760 ERROR ps.ParameterServer: send heartbeat to appmaster failed 
java.lang.OutOfMemoryError: Java heap space
	at com.tencent.angel.ml.math2.storage.IntIntDenseVectorStorage.<init>(IntIntDenseVectorStorage.java:26)
	at com.tencent.angel.ml.math2.VFactory.denseIntVector(VFactory.java:95)
	at com.tencent.angel.ps.storage.vector.ServerRow.initRow(ServerRow.java:489)
	at com.tencent.angel.ps.storage.vector.ServerRow.<init>(ServerRow.java:92)
	at com.tencent.angel.ps.storage.vector.ServerIntIntRow.<init>(ServerIntIntRow.java:64)
	at com.tencent.angel.ps.storage.vector.ServerIntIntRow.<init>(ServerIntIntRow.java:80)
	at com.tencent.angel.ps.storage.vector.ServerRowFactory.createServerRow(ServerRowFactory.java:109)
	at com.tencent.angel.ps.storage.matrix.ServerPartition.initRow(ServerPartition.java:139)
	at com.tencent.angel.ps.storage.matrix.ServerPartition.initRows(ServerPartition.java:131)
	at com.tencent.angel.ps.storage.matrix.ServerPartition.init(ServerPartition.java:122)
	at com.tencent.angel.ps.storage.matrix.ServerMatrix.init(ServerMatrix.java:91)
	at com.tencent.angel.ps.storage.MatrixStorageManager.addMatrix(MatrixStorageManager.java:106)
	at com.tencent.angel.ps.storage.MatrixStorageManager.addMatrices(MatrixStorageManager.java:89)
	at com.tencent.angel.ps.ParameterServer.createMatrices(ParameterServer.java:643)
	at com.tencent.angel.ps.ParameterServer.syncMatrices(ParameterServer.java:615)
	at com.tencent.angel.ps.ParameterServer.heartbeat(ParameterServer.java:603)
	at com.tencent.angel.ps.ParameterServer.lambda$startHeartbeat$0(ParameterServer.java:516)
	at com.tencent.angel.ps.ParameterServer$$Lambda$13/1916557746.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
2018-09-20 15:23:18,773 INFO ps.ParameterServer: stop ps rpcServer!
2018-09-20 15:23:18,773 INFO ipc.NettyServer: Stopping server on 26737
2018-09-20 15:23:18,794 INFO ps.ParameterServer: stop heartbeat thread!
2018-09-20 15:23:18,794 WARN ps.ParameterServer: InterruptedException while stopping heartbeatThread.

是我的配置不对吗？

**Comment by leleyu** [comment]
I think you are running with local mode. When local mode, the memory setting for master/worker/ps is not working. They are all residing in one JVM process and the JVM size is set with the command line you start the local process. Defaultly I think it is 512MB.
