### ISSUE TITLE
encoded string too long in angel-2.0.0-alpha when FM training with big model

### ISSUE THREAD

**Issue by Suanec** [Angel-ML/angel#441]
I found an exception ```encoded string too long: 259553 bytes``` when I trained the FM in angel-2.0.0-alpha.

> The trained model has parameters more than `$10^{9}$`

The detail :
```shell
com.tencent.angel.exception.AngelException: Model save falied move output files for matrice failed, error msg = move output files for matrix embedding_embedding failed, error msg = java.io.UTFDataFormatException: encoded string too long: 259553 bytes
  at com.tencent.angel.client.AngelClient.isSaveCompleted(AngelClient.java:512)
  at com.tencent.angel.client.AngelClient.save(AngelClient.java:278)
  at com.tencent.angel.ml.core.network.layers.AngelGraph.saveModel(AngelGraph.scala:184)
  at com.tencent.angel.ml.core.graphsubmit.GraphModel.saveModel(GraphModel.scala:142)
  at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:59)
  at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:88)
  at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:29)
  at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:69)
  at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:56)
  at java.security.AccessController.doPrivileged(Native Method)
  at javax.security.auth.Subject.doAs(Subject.java:422)
  at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
  at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:56)
  at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:40)
```

I trace the bug and the error info. found the exception throwed by 
``` output.writeUTF(jsonObject.toString());``` in ```./angel-ps/core/src/main/java/com/tencent/angel/model/output/format/MatrixFilesMeta.java```

It was caused by ```writeUTF``` implement in ```***/java/io/DataOutputStream.java``` with hard-encode such as :

```java

    if (utflen > 65535)
        throw new UTFDataFormatException(
            "encoded string too long: " + utflen + " bytes");
    

```

I fix the problem manurally in ```./angel-ps/core/src/main/java/com/tencent/angel/model/output/format/MatrixFilesMeta.java``` with a naivy modification 
```java
-      output.writeUTF(jsonObject.toString());
+      String jsos =  jsonObject.toString();
+      int bufferSize = 60000;
+      int i =0;
+      int sum = 0;
+
+      while(i < jsos.length()){
+          int endIdx = java.lang.Math.min(jsos.length(),i+bufferSize);
+          String jsosPart = jsos.substring(i,endIdx);
+          output.writeUTF(jsosPart);
+          sum += jsosPart.length();
+          i += bufferSize;
+      }
+      assert sum == jsos.length();
+//      output.writeUTF(jsonObject.toString());
```

**Comment by Suanec** [comment]
Fixed by #442
- [BUG] encoded string too long bug fixed in MatrixFilesMeta when save matrix meta. #442
