### ISSUE TITLE
com.tencent.angel.ps.server.data.WorkerPool: handle request  INDEX_GET_ROWS failed  java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by ljwei** [Angel-ML/angel#553]
at com.tencent.angel.ml.math2.storage.IntFloatDenseVectorStorage.get(IntFloatDenseVectorStorage.java:30)
	at com.tencent.angel.ml.math2.vector.IntFloatVector.get(IntFloatVector.java:62)
	at com.tencent.angel.ps.storage.vector.ServerIntFloatRow.get(ServerIntFloatRow.java:106)
	at com.tencent.angel.ps.storage.vector.ServerIntFloatRow.indexGet(ServerIntFloatRow.java:430)
	at com.tencent.angel.ps.server.data.WorkerPool.handleIndexGetRows(WorkerPool.java:628)
	at com.tencent.angel.ps.server.data.WorkerPool.handle(WorkerPool.java:448)
	at com.tencent.angel.ps.server.data.WorkerPool.handlerRequest(WorkerPool.java:228)
	at com.tencent.angel.ps.server.data.MatrixTransportServerHandler.channelRead(MatrixTransportServerHandler.java:54)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)

**Comment by paynie** [comment]
The format of training data is libsvm ?  Please check the start index is 0 or 1

**Comment by ljwei** [comment]
yes,libsvm. when i start with 1, it's ok. but when i start with 0,  throw this exception.

**Comment by wangcaihua** [comment]
Hi, the libsvm format require the index start with 1. As a result, angel throws exception when it start with 0. 
For detail information , pls. refer: https://github.com/wangcaihua/angel/blob/master/docs/algo/data_format.md

**Comment by ljwei** [comment]
ok, thank you!
