### ISSUE TITLE
FM load Model ERROR

### ISSUE THREAD

**Issue by Cynus** [Angel-ML/angel#593]
**After training a FM model with your example config successfully,I want to append train my saved model but throw out an excetion.The exception also happened when I try to predict data.
My script is:**
./angel-yarn-submit.sh \
	-Dangel.train.data.path="hdfs://blablabla/dataset/1219_fm_two" \
	-Dangel.app.submit.class=com.tencent.angel.ml.core.graphsubmit.GraphRunner \
	-Dangel.log.path="hdfs://blablabla/test/log/1219_fm_two_13_1" \
	-Dangel.save.model.path="hdfs://blablabla/model/1219_fm_two_13_1" \
	-Dangel.load.model.path="hdfs://blablabla/model/1219_fm_two_13" \
	-Daction.type=train \
	-Dml.model.class.name=com.tencent.angel.ml.classification.FactorizationMachines \
	-Dml.epoch.num=3 \
	-Dml.data.type=dummy \
	-Dml.feature.index.range=6584759 \
	-Dml.model.size=6584759 \
	-Dml.data.validate.ratio=0.1 \
	-Dml.inputlayer.optimizer=sgd \
	-Dml.learn.rate=0.1 \
	-Dml.learn.decay=0.5 \
	-Dml.reg.l2=0.001 \
	-Dml.fm.field.num=1050 \
	-Dml.fm.rank=8 \
	-Dangel.job.name=Angel_FM_13_1 \
	-Dangel.am.memory.gb=8 \
	-Dangel.workergroup.number=1500 \
	-Dangel.worker.task.number=1 \
	-Dangel.worker.memory.gb=10 \
	-Dangel.worker.cpu.vcores=5 \
	-Dangel.ps.number=300 \
	-Dangel.ps.memory.gb=10 \
	-Dangel.ps.cpu.vcores=1 \
	-Dangel.tmp.output.path.prefix="/blablabla/test/tmp" \
	-Dangel.job.dir="hdfs://blablabla/test/tmp/job" \
	-Dangel.staging.dir="hdfs://blablabla/test/tmp/hadoop-yarn" \
	-Dangel.am.env="JAVA_HOME=/blablabla/jdk1.8" \
	-Dangel.worker.env="JAVA_HOME=/blablabla/jdk1.8" \
	-Dangel.ps.env="JAVA_HOME=/blablabla/jdk1.8"

**Here is the log:**
18/12/21 17:51:03 INFO yarn.AngelYarnClient: start to create rpc client to am
18/12/21 17:51:04 INFO client.AngelClient: clientId=1
18/12/21 17:51:54 INFO yarn.AngelYarnClient: start pss success
18/12/21 17:52:05 ERROR client.AngelClient: save model failed.
com.google.protobuf.ServiceException: java.util.concurrent.ExecutionException: java.io.IOException: Read matrix meta failed
	at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:317)
	at com.sun.proxy.$Proxy17.load(Unknown Source)
	at com.tencent.angel.client.AngelClient.load(AngelClient.java:369)
	at com.tencent.angel.ml.core.network.layers.AngelGraph.loadModel(AngelGraph.scala:183)
	at com.tencent.angel.ml.core.graphsubmit.GraphModel.loadModel(GraphModel.scala:163)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:59)
	at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:88)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:29)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:69)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:56)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:56)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:40)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Read matrix meta failed
	at com.tencent.angel.ipc.CallFuture.get(CallFuture.java:121)
	at com.tencent.angel.ipc.NettyTransceiver.call(NettyTransceiver.java:297)
	at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:294)
	... 14 more
Caused by: java.io.IOException: Read matrix meta failed
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.tencent.angel.exception.RemoteException.instantiateException(RemoteException.java:72)
	at com.tencent.angel.exception.RemoteException.unwrapRemoteException(RemoteException.java:58)
	at com.tencent.angel.ipc.NettyTransceiver$TransceiverCallback.handleResult(NettyTransceiver.java:420)
	at com.tencent.angel.ipc.NettyTransceiver$TransceiverCallback.handleResult(NettyTransceiver.java:357)
	at com.tencent.angel.ipc.NettyTransceiver$MLClientMLHandler.channelRead(NettyTransceiver.java:472)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.tencent.angel.exception.RemoteException: Read matrix meta failed
	at com.tencent.angel.ipc.NettyTransceiver$TransceiverCallback.handleResult(NettyTransceiver.java:419)
	... 30 more
18/12/21 17:52:06 INFO client.AngelClient: stop the application
18/12/21 17:52:06 INFO client.AngelClient: master is not null, send stop command to Master, stateCode=0
18/12/21 17:52:06 ERROR utils.AngelRunJar: submit job failed
com.tencent.angel.exception.AngelException: com.google.protobuf.ServiceException: java.util.concurrent.ExecutionException: java.io.IOException: Read matrix meta failed
	at com.tencent.angel.client.AngelClient.load(AngelClient.java:373)
	at com.tencent.angel.ml.core.network.layers.AngelGraph.loadModel(AngelGraph.scala:183)
	at com.tencent.angel.ml.core.graphsubmit.GraphModel.loadModel(GraphModel.scala:163)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:59)
	at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:88)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:29)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:69)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:56)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:56)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:40)
Caused by: com.google.protobuf.ServiceException: java.util.concurrent.ExecutionException: java.io.IOException: Read matrix meta failed
	at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:317)
	at com.sun.proxy.$Proxy17.load(Unknown Source)
	at com.tencent.angel.client.AngelClient.load(AngelClient.java:369)
	... 12 more
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Read matrix meta failed
	at com.tencent.angel.ipc.CallFuture.get(CallFuture.java:121)
	at com.tencent.angel.ipc.NettyTransceiver.call(NettyTransceiver.java:297)
	at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:294)
	... 14 more
Caused by: java.io.IOException: Read matrix meta failed
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.tencent.angel.exception.RemoteException.instantiateException(RemoteException.java:72)
	at com.tencent.angel.exception.RemoteException.unwrapRemoteException(RemoteException.java:58)
	at com.tencent.angel.ipc.NettyTransceiver$TransceiverCallback.handleResult(NettyTransceiver.java:420)
	at com.tencent.angel.ipc.NettyTransceiver$TransceiverCallback.handleResult(NettyTransceiver.java:357)
	at com.tencent.angel.ipc.NettyTransceiver$MLClientMLHandler.channelRead(NettyTransceiver.java:472)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.tencent.angel.exception.RemoteException: Read matrix meta failed
	at com.tencent.angel.ipc.NettyTransceiver$TransceiverCallback.handleResult(NettyTransceiver.java:419)
	... 30 more

**Comment by paynie** [comment]
You can provide the Master log and PS log here. The method to get these logs is like this: https://github.com/Angel-ML/angel/wiki/%E5%B7%A5%E7%A8%8B%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by paynie** [comment]
https://github.com/Angel-ML/angel/issues/596
It is a known bug for branch-2.0.0, i merge a commit from hotfix branch just now. You can pull branch-2.0.0 or use branch-2.0.1.

**Comment by Cynus** [comment]
That works
