### ISSUE TITLE
Load failed for the matrix that has many partitions

### ISSUE THREAD

**Issue by paynie** [Angel-ML/angel#596]
Caused by: java.io.IOException: org.codehaus.jettison.json.JSONException: Expected a ':' after a key at character 65533 of {"matrixId":0,"matrixName":"input_weight","formatClassName":"com.tencent.angel.model.output.format.ColIdValueTextRowFormat","rowType":7,"row":2,"col":6584759,"blockRow":2,"blockCol":21949,"options":{},"partMetas":{"0":{"partId":0,"startRow":0,"endRow":2,"startCol":0,"endCol":21949,"nnz":21949,"saveRowNum":1,"saveColNum":0,"saveColElemNum":0,"fileName":"0","offset":0,"length":408050,"rowMetas":{"0":{"rowId":0,"offset":0,"elementNum":21949,"saveType":0}}},...........rowMetas":{"0":{"rowId":0,"offset"
at com.tencent.angel.model.output.format.MatrixFilesMeta.read(MatrixFilesMeta.java:272)
at com.tencent.angel.master.matrix.committer.AMModelLoader.split(AMModelLoader.java:326)
... 33 more

**Comment by paynie** [comment]
Resolved
