### ISSUE TITLE
How can I specify Angel App Master running on a specific IP node rather than on one of the YARN node?

### ISSUE THREAD

**Issue by zxsimple** [Angel-ML/angel#620]
When I `angel-submit` job with `YARN` mode, Angel will allocate `AngelWebApp` running on one of the node manager.
```
webApp =WebApps.$for("angel", AMContext.class, appContext).with(conf).start(new AngelWebApp());
```
The problem is that the System Env variable is different from that client where I submit the job, it cause much permission problem regarding reading Haddop configuration files.

Is that possible to start the Angel AM on my client machine with fixed IP address?

**Comment by paynie** [comment]
Yarn does not support launching App Master on a specified node now.  You can describe your problem in more detail ？

**Comment by zxsimple** [comment]
Actually it has file read permission problem while start YARN WebApp, see:
```
2019-01-14 18:51:04,222 FATAL [main] org.apache.hadoop.conf.Configuration: error parsing conf ssl-server.xml
java.io.FileNotFoundException: /opt/xxx/xxx/xxx/xxx/etc/ssl-server.xml (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at java.net.URL.openStream(URL.java:1045)
        at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2571)
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2783)
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2605)
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2485)
        at org.apache.hadoop.conf.Configuration.get(Configuration.java:1004)
        at org.apache.hadoop.conf.Configuration.getStringCollection(Configuration.java:1871)
        at org.apache.hadoop.security.alias.CredentialProviderFactory.getProviders(CredentialProviderFactory.java:64)
        at org.apache.hadoop.conf.Configuration.getPasswordFromCredentialProviders(Configuration.java:2000)
        at org.apache.hadoop.conf.Configuration.getPassword(Configuration.java:1980)
        at org.apache.hadoop.yarn.webapp.util.WebAppUtils.getPassword(WebAppUtils.java:400)
        at org.apache.hadoop.yarn.webapp.util.WebAppUtils.loadSslConfiguration(WebAppUtils.java:376)
        at org.apache.hadoop.yarn.webapp.WebApps$Builder.build(WebApps.java:283)
        at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:359)
        at com.tencent.angel.master.AngelApplicationMaster.initAndStart(AngelApplicationMaster.java:842)
        at com.tencent.angel.master.AngelApplicationMaster$1.run(AngelApplicationMaster.java:679)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1778)
        at com.tencent.angel.master.AngelApplicationMaster.main(AngelApplicationMaster.java:677)
```
Inside the `AngelApplicationMaster` I get all the ENV variables and see that `HADOOP_CONF_DIR` and other Hadoop variable as `/opt/xxx/xxx/xxx/xxx/`, we can't going to change the file permission in large cluster. While my hadoop client machine the `HADOOP_CONF_DIR`  and others refer to totally different path. So I raise the issue, now my work around is to setting the YARN WebApp HTTP policy to HTTP rather than HTTPS.
```
<property>
    <name>yarn.http.policy</name>
    <!-- <value>HTTPS_ONLY</value> -->
    <value>HTTP_ONLY</value>
</property>
```
