### ISSUE TITLE
java.lang.NullPointerException &  submit application to yarn failed.

### ISSUE THREAD

**Issue by ibingoogle** [Angel-ML/angel#628]
Hi all:

I submit Logistic Regression job to Yarn cluster (not Spark on Angel job, just Angel job) today
Angel version is 2.0.1
Hadoop/Yarn version is 2.9.2, cluster has 9 nodes, each one is ocnfigured with 16GB and 8 vcores
The Yarn cluster has been tested that it works well with MapReduce jobs

the submission command is:
**_**./angel-submit \
	-Dml.epoch.num=2 \
    -Dangel.app.submit.class=com.tencent.angel.ml.core.graphsubmit.GraphRunner \
    -Dml.model.class.name=com.tencent.angel.ml.classification.LogisticRegression \
    -Dml.feature.index.range=3300000 \
    -Dml.model.size=3300000 \
    -Dml.data.validate.ratio=0.1 \
    -Dml.data.type=libsvm \
    -Dml.learn.rate=0.1 \
    -Dml.reg.l2=0.03 \
    -Daction.type=train \
    -Dml.inputlayer.optimizer=ftrl \
    -Dangel.train.data.path=hdfs://hadoop1master:8020/angel/ps/examples/LogisticRegression/input/url \
-Dangel.save.model.path=hdfs://hadoop1master:8020/angel/ps/examples/LogisticRegression/model \
	-Dangel.log.path=hdfs://hadoop1master:8020/angel/ps/examples/LogisticRegression/log \
    -Dangel.workergroup.number=2 \
    -Dangel.worker.memory.gb=4 \
    -Dangel.worker.task.number=1 \
    -Dangel.ps.number=2 \
    -Dangel.ps.memory.gb=4 \
	-Dangel.am.memory.gb=4 \
    -Dangel.task.data.storage.level=memory \
    -Dangel.job.name=angel_LR_url_train**_**

However, java.lang.NullPointerException error occurs as follows (this is the log in the terminal):

**_
AppMaster capability = <memory:4096, vCores:1>
19/01/16 17:22:05 INFO yarn.AngelYarnClient: Command to launch container for ApplicationMaster is : $JAVA_HOME/bin/java -Dlog4j.configuration=log/angel.properties -Dlog4j.logger.com.tencent.ml=DEBUG -Dyarn.app.container.log.dir=<LOG_DIR> -Dyarn.app.container.log.filesize=0 -Dhadoop.root.logger=INFO,CLA  -Xmx1536M -Xms1536M -XX:PermSize=100M -XX:MaxPermSize=200M -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintCommandLineFlags -XX:+PrintTenuringDistribution -XX:+PrintAdaptiveSizePolicy -Xloggc:<LOG_DIR>/gc.log com.tencent.angel.master.AngelApplicationMaster 1><LOG_DIR>/stdout 2><LOG_DIR>/stderr 
19/01/16 17:22:05 INFO util.AngelApps: yarn.application.classpath=null
19/01/16 17:22:05 INFO util.AngelApps: mapreduce.application.classpath=null
19/01/16 17:22:05 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename :  default
19/01/16 17:22:05 INFO impl.YarnClientImpl: Submitted application application_1547683746122_0005
19/01/16 17:22:11 INFO yarn.AngelYarnClient: application is finished!!
19/01/16 17:22:11 ERROR yarn.AngelYarnClient: submit application to yarn failed.
java.lang.NullPointerException
	at com.tencent.angel.client.AngelClient.waitForAllPS(AngelClient.java:1041)
	at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:172)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:55)
	at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:88)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:29)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:69)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:56)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:56)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:40)
19/01/16 17:22:11 INFO client.AngelClient: stop the application
19/01/16 17:22:11 INFO client.AngelClient: master is null, just kill the application
19/01/16 17:22:11 INFO impl.YarnClientImpl: Killed application application_1547683746122_0005
19/01/16 17:22:11 ERROR utils.AngelRunJar: submit job failed 
com.tencent.angel.exception.AngelException: java.lang.NullPointerException
	at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:176)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:55)
	at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:88)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:29)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:69)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:56)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:56)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:40)
Caused by: java.lang.NullPointerException
	at com.tencent.angel.client.AngelClient.waitForAllPS(AngelClient.java:1041)
	at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:172)
	... 10 more_**

I also check the Syslog in container:
**_
2019-01-16 22:11:24,987 INFO [AsyncDispatcher event handler] com.tencent.angel.master.ps.attempt.PSAttempt: allocate ps server attempt resource, ps attempt id = PSAttempt_0_0
2019-01-16 22:11:24,988 INFO [AsyncDispatcher event handler] com.tencent.angel.master.ps.attempt.PSAttempt: PSAttempt_0_0 PSAttempt Transitioned from NEW to SCHEDULED
2019-01-16 22:11:24,988 INFO [AsyncDispatcher event handler] com.tencent.angel.master.ps.attempt.PSAttempt: allocate ps server attempt resource, ps attempt id = PSAttempt_1_0
2019-01-16 22:11:24,988 INFO [AsyncDispatcher event handler] com.tencent.angel.master.ps.attempt.PSAttempt: PSAttempt_1_0 PSAttempt Transitioned from NEW to SCHEDULED
2019-01-16 22:11:25,012 FATAL [Thread-18] com.tencent.angel.master.deploy.ContainerAllocator: Error in handling event type CONTAINER_REQ to the ContainreAllocator
java.lang.NullPointerException
	at org.apache.hadoop.yarn.api.records.ResourceRequest$ResourceRequestComparator.compare(ResourceRequest.java:289)
	at org.apache.hadoop.yarn.api.records.ResourceRequest$ResourceRequestComparator.compare(ResourceRequest.java:267)
	at java.util.TreeMap.compare(TreeMap.java:1291)
	at java.util.TreeMap.put(TreeMap.java:538)
	at java.util.TreeSet.add(TreeSet.java:255)
	at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator.addResourceRequestToAsk(YarnContainerAllocator.java:690)
	at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator.addResourceRequest(YarnContainerAllocator.java:677)
	at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator.addResourceRequest(YarnContainerAllocator.java:647)
	at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator.requestContainer(YarnContainerAllocator.java:566)
	at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator.handleEvent(YarnContainerAllocator.java:519)
	at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator$2.run(YarnContainerAllocator.java:588)
2019-01-16 22:11:25,022 FATAL [Thread-18] com.tencent.angel.master.app.InternalErrorEvent: Error in handling event type CONTAINER_REQ to the ContainreAllocatornull
2019-01-16 22:11:25,023 INFO [AsyncDispatcher event handler] com.tencent.angel.master.app.App: some error happened, InternalErrorEvent [errorMsg=Error in handling event type CONTAINER_REQ to the ContainreAllocatornull, getType()=INTERNAL_ERROR]
2019-01-16 22:11:25,023 INFO [AsyncDispatcher event handler] com.tencent.angel.master.app.App: application_1547701843662_0001Job Transitioned from NEW to FAILED
2019-01-16 22:11:25,027 INFO [Thread-28] com.tencent.angel.master.AngelApplicationMaster: Calling stop for all the services
2019-01-16 22:11:25,029 WARN [Heartbeat Timeout checker] com.tencent.angel.master.HeartbeatMonitor: Heartbeat Timeout checker is interupted
2019-01-16 22:11:25,030 INFO [Thread-28] com.tencent.angel.master.HeartbeatMonitor: Heartbeat monitor stopped
2019-01-16 22:11:25,038 INFO [Thread-28] com.tencent.angel.master.matrix.committer.AMModelSaver: Model saver stopped
2019-01-16 22:11:25,041 INFO [Thread-28] com.tencent.angel.master.metrics.MetricsService: MasterService stopped
2019-01-16 22:11:25,041 INFO [Thread-28] com.tencent.angel.master.slowcheck.SlowChecker: Slow checker stopped
2019-01-16 22:11:25,041 INFO [Thread-28] com.tencent.angel.master.ps.ParameterServerManager: ParameterServerManager stopped
2019-01-16 22:11:25,041 INFO [Thread-28] com.tencent.angel.master.deploy.ContainerLauncher: ContainerLauncher stopped
2019-01-16 22:11:25,042 INFO [Thread-28] com.tencent.angel.master.deploy.ContainerAllocator: to unregister from Yarn RM
2019-01-16 22:11:25,051 FATAL [RMCommunicator Allocator] com.tencent.angel.master.deploy.ContainerAllocator: register am to rm failed. java.io.InterruptedIOException: Call interrupted
2019-01-16 22:11:25,051 FATAL [RMCommunicator Allocator] com.tencent.angel.master.app.InternalErrorEvent: register am to rm failed. Call interrupted
2019-01-16 22:11:25,051 WARN [RMCommunicator Allocator] org.apache.hadoop.yarn.event.AsyncDispatcher: AsyncDispatcher thread interrupted
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
	at org.apache.hadoop.yarn.event.AsyncDispatcher$GenericEventHandler.handle(AsyncDispatcher.java:269)
	at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator$1.run(YarnContainerAllocator.java:253)
	at java.lang.Thread.run(Thread.java:745)
2019-01-16 22:11:25,052 ERROR [RMCommunicator Allocator] org.apache.hadoop.yarn.YarnUncaughtExceptionHandler: Thread Thread[RMCommunicator Allocator,5,main] threw an Exception.
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.yarn.event.AsyncDispatcher$GenericEventHandler.handle(AsyncDispatcher.java:277)
	at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator$1.run(YarnContainerAllocator.java:253)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
	at org.apache.hadoop.yarn.event.AsyncDispatcher$GenericEventHandler.handle(AsyncDispatcher.java:269)
	... 2 more
2019-01-16 22:11:25,052 INFO [Thread-28] com.tencent.angel.master.deploy.ContainerAllocator: Setting job diagnostics to Error in handling event type CONTAINER_REQ to the ContainreAllocatornull

2019-01-16 22:11:25,069 INFO [Thread-28] com.tencent.angel.master.deploy.ContainerAllocator: Waiting for application to be successfully unregistered.
2019-01-16 22:11:25,146 INFO [main] com.tencent.angel.master.AngelApplicationMaster: appAttemptId.getAttemptId()=1
2019-01-16 22:11:30,072 INFO [Thread-28] com.tencent.angel.master.deploy.ContainerAllocator: ContainerAllocator service stop!
2019-01-16 22:11:30,073 INFO [Thread-28] com.tencent.angel.master.oplog.AppStateStorage: app-state-writter service stop!
2019-01-16 22:11:30,073 INFO [Thread-28] com.tencent.angel.master.app.App: App manager stopped
2019-01-16 22:11:30,073 INFO [Thread-28] com.tencent.angel.master.AngelApplicationMaster: start to write app state to file and clear tmp directory
2019-01-16 22:11:30,073 INFO [Thread-28] com.tencent.angel.master.AngelApplicationMaster: start to write app state to file hdfs://hadoop1master:8020/tmp/hadoop0master/application_1547701843662_0001_c609e8a2-70d1-4dd9-9166-0185b3eb8ea0/state
2019-01-16 22:11:30,103 INFO [Thread-28] com.tencent.angel.master.app.App: write app report to file successfully jobReport {
  jobState: J_FAILED
  curIteration: 0
  totalIteration: 100
  diagnostics: "Error in handling event type CONTAINER_REQ to the ContainreAllocatornull"
}

2019-01-16 22:11:30,120 INFO [Thread-28] com.tencent.angel.master.AngelApplicationMaster: write app state over
2019-01-16 22:11:30,121 INFO [Thread-28] com.tencent.angel.master.AngelApplicationMaster: Deleting staging directory hdfs://hadoop1master:8020 /tmp/hadoop-yarn/hadoop0master/.staging/application_1547701843662_0001
2019-01-16 22:11:30,127 INFO [Thread-28] com.tencent.angel.master.AngelApplicationMaster: Deleting tmp output directory hdfs://hadoop1master:8020/tmp/hadoop0master/application_1547701843662_0001_794927ab-1e17-406c-8369-4a5aeccbfbbf
2019-01-16 22:11:40,129 INFO [Thread-28] com.tencent.angel.ipc.NettyServer: Stopping server on 26564
2019-01-16 22:11:40,134 INFO [Thread-28] com.tencent.angel.master.MasterService: WorkerPSService is stoped!
2019-01-16 22:11:40,134 INFO [Thread-28] com.tencent.angel.master.AngelApplicationMaster: Exiting Angel AppMaster..GoodBye!
2019-01-16 22:11:40,140 INFO [shutdown-hook-0] com.tencent.angel.master.AngelApplicationMaster: AM received a signal. stop the app
_**

Can anyone help me figure out why this happens? 
thanks

**Comment by ibingoogle** [comment]
I just try to submit the same Angel job to Yarn cluster with version 2.8.3. And it works!
So, is it possible that current angel 2.0.1 job is incompatible with Yarn version 2.9.2?

**Comment by ouyangwen-it** [comment]
> I just try to submit the same Angel job to Yarn cluster with version 2.8.3. And it works!
> So, is it possible that current angel 2.0.1 job is incompatible with Yarn version 2.9.2?

 if you want angel 2.0.1 on hadoop 2.9.2 works，you need change several api according the diff.patch file, then try repackage it.
[diff.patch.txt](https://github.com/Angel-ML/angel/files/2771816/diff.patch.txt)

**Comment by haoyangOxford** [comment]
Hi, I also got trouble [issue#640](https://github.com/Angel-ML/angel/issues/640) submitting the same Angel job to Yarn cluster with version 2.7.6. Any idea?

**Comment by ouyangwen-it** [comment]
> Hi, I also got trouble [issue#640](https://github.com/Angel-ML/angel/issues/640) submitting the same Angel job to Yarn cluster with version 2.7.6. Any idea?

maybe not  the same problem，please paste full logs，Syslog in container， am logs etc.

**Comment by wjlight** [comment]
hi, angel3.0 is incompatible with Yarn version 3.1

**Comment by ouyangwen-it** [comment]
> hi, angel3.0 is incompatible with Yarn version 3.1?

you can pull branch-3.0.1-hadoop3, and it support hadoop3 above.
