### ISSUE TITLE
求助，2.0.0的Word2vecExample训练不稳定

### ISSUE THREAD

**Issue by cuiwei133** [Angel-ML/angel#730]
我在测试angel的分布式的word2vec，遇到的问题是我在跑模型的过程中，经常遇到这种问题，Caused by: com.tencent.angel.exception.PSRPCException: Sub-Task 0 execution failed, failed message=get row split fatal error happened update UpdaterRequest [updaterFuncClass=com.tencent.angel.spark.ml.psf.embedding.w2v.Adjust, partParam=com.tencent.angel.spark.ml.psf.embedding.w2v.AdjustPartitionParam@1bdf19d8, toString()=PartitionRequest{clock=0, partKey=PartitionKey(matrixId=2, partitionId=9, startRow=0, startCol=129492504, endRow=1, endCol=143880560)indexNum=-1), comeFromPs=false} com.tencent.angel.ps.server.data.request.UpdaterRequest@20bf67] failed java.lang.ArrayIndexOutOfBoundsException
at com.tencent.angel.psagent.matrix.transport.FutureResult.get(FutureResult.java:66)
    at com.tencent.angel.spark.ml.embedding.NEModel.psfUpdate(NEModel.scala:198)
    at com.tencent.angel.spark.ml.embedding.NEModel.com$tencent$angel$spark$ml$embedding$NEModel$$sgdForBatch$1(NEModel.scala:174)
    at com.tencent.angel.spark.ml.embedding.NEModel$$anonfun$sgdForPartition$1.apply(NEModel.scala:186)
    at com.tencent.angel.spark.ml.embedding.NEModel$$anonfun$sgdForPartition$1.apply(NEModel.scala:185)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
    at scala.collection.AbstractIterator.to(Iterator.scala:1336)
    at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
    at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
    at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
    at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
    at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:893)
    at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:893)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1897)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1897)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
    at org.apache.spark.scheduler.Task.run(Task.scala:85)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
造成训练不稳定，有时候能跑完，有时候重试到上限之后任务就死掉了，麻烦问下这可能是什么原因呢
我用原工程里面给的text8测试没有出这种错。。。
还有，在迭代部分是没有问题的..到最后一轮大面积出这种错。。。求指教。。

**Comment by ghandzhipeng** [comment]
能贴下你的启动脚本吗？

**Comment by cuiwei133** [comment]
$SPARK_HOME/bin/spark-submit \
    --master yarn-cluster \
    --conf spark.hadoop.fs.defaultFS=hdfs://ns3-backup/user/weibo_bigdata_push/spark_angel \
    --conf spark.ps.out.tmp.path.prefix=/user/weibo_bigdata_push/spark_angel_tmp \
    --conf spark.ps.staging.dir=/user/weibo_bigdata_push/angel_staging \
    --conf spark.dynamicAllocation.enabled=false \
    --conf spark.yarn.stagingDir=/user/weibo_bigdata_push/spark_angel_taging \
    --conf spark.ps.jars=$SONA_ANGEL_JARS \
    --conf spark.ps.instances=10 \
    --conf spark.ps.cores=2 \
    --conf spark.ps.memory=20g \
    --jars $SONA_SPARK_JARS \
    --name "word2vec-spark" \
    --driver-memory 10g \
    --num-executors 50 \
    --executor-cores 2 \
    --executor-memory 16g \
    --class com.tencent.angel.spark.examples.cluster.Word2vecExample \
    $ANGEL_HOME/lib/spark-on-angel-examples-2.1.0.jar \
    input:$input \
    output:$output \
    embedding:16 \
    numParts:16 \
    subSample:false \
    negative:5 \
    window:10 \
    epoch:30 \
    batchSize:128 \
    interval:1


训练数据大概60g，item大小在8kw左右

**Comment by ghandzhipeng** [comment]
看着log是从ps拉取模型的时候越界了，可能是对应的ps挂了，得结合具体的日志去看。
您可以自己查看一下log， 或者将log贴上来。

**Comment by cuiwei133** [comment]
嗯，是的，听一位同事加大了ps节点的内存和节点数，这个问题已经解决了，非常感谢您的回复
目前的问题是单轮训练的时长一直降不下来，还在看日志中
您有什么建议么？
目前的情况是：单轮在1.4h，矩阵计算的时间大概在40%左右，更新梯度可以忽略不计，update大概60%
100worker*1core*15g ps:60*1*15g，模型大概10多个g，总样本量60g左右

**Comment by ghandzhipeng** [comment]
可以加大batch size，适当减少PS的数目。另外现在您的embedding 维度只有16，而angel现在的word2vec实现是按照模型列切分的，所以加多ps的数目可能会带来比较大的通信开销。

比如：
$SPARK_HOME/bin/spark-submit 
--master yarn-cluster 
--conf spark.hadoop.fs.defaultFS=$defaultFS 
--conf spark.ps.out.tmp.path.prefix=/user/cuiwei/spark_angel_tmp 
--conf spark.ps.staging.dir=/user/cuiwei/angel_staging 
--conf spark.dynamicAllocation.enabled=false 
--conf spark.yarn.stagingDir=/user/cuiwei/spark_angel_taging 
--conf spark.ps.jars=$SONA_ANGEL_JARS 
--conf spark.ps.instances=4 
--conf spark.ps.cores=2 
--conf spark.ps.memory=20g 
--jars $SONA_SPARK_JARS 
--name "word2vec-spark" 
--driver-memory 10g 
--num-executors 15
--executor-cores 2 
--executor-memory 10g 
--class com.tencent.angel.spark.examples.cluster.Word2vecExample 
$ANGEL_HOME/lib/spark-on-angel-examples-2.1.0.jar 
input:$input 
output:$output 
embedding:16 
numParts:16 
subSample:false 
negative:5 
window:10 
epoch:30 
batchSize:1280
interval:1

如果想增加embedding 维度的话可以再增加PS的数目。

**Comment by ghandzhipeng** [comment]
可以看看这个文档：
https://github.com/Angel-ML/angel/blob/master/docs/algo/sona/word2vec_sona.md
