### ISSUE TITLE
serving multiple model load issue

### ISSUE THREAD

**Issue by mattxia** [Angel-ML/angel#732]
1.on Window system
2.multiple model in one config file as follows:
model_config_list: {
config: {
name: "lr",
base_path: "D:/prj/angel/serving-develop/serving-develop/models/angel/lr/lr-model",
model_platform: "Angel",
model_version_policy: {
latest: {
num_versions: 1
}
}
},
config: {
name: "deepfm",
base_path: "D:/prj/angel/serving-develop/serving-develop/models/angel/deepFM/deepFM-model",
model_platform: "Angel",
model_version_policy: {
latest: {
num_versions: 1
}
}
}
}
3.deep fm load successfully
4.but lr load failed , I think driven by event?
19/04/18 11:05:48 INFO angel.AngelSavedModelBundle$ : model load path is D:\prj\angel\serving-develop\serving-develop\models\angel\lr\lr-model\6 
19/04/18 11:06:04 INFO angel.AngelSavedModelBundle$ : buildNetwork for model{"ml.data.posneg.ratio":"-1.0","ml.fclayer.matrix.output.format":"com.tencent.angel.model.output.format.RowIdColIdValueTextRowFormat","ml.reg.l1":"0.0","ml.embedding.matrix.output.format":"com.tencent.angel.model.output.format.TextColumnFormat","ml.minibatch.size":"128","angel.load.model.path":"D:\\prj\\angel\\serving-develop\\serving-develop\\models\\angel\\lr\\lr-model\\6","ml.num.update.per.epoch":"10","ml.optimizer.json.provider":"com.tencent.angel.ml.core.local.LocalOptimizerProvider","ml.field.num":"13","ml.batch.sample.ratio":"1.0","ml.epoch.num":"10","ml.feature.index.range":"123","ml.data.validate.ratio":"0.1","ml.opt.momentum.momentum":"0.9","ml.data.type":"libsvm","ml.data.label.trans.class":"NoTrans","ml.learn.rate":"0.5","ml.json.conf.file":"D:\\prj\\angel\\serving-develop\\serving-develop\\models\\angel\\lr\\lr-model\\6\\graph.json","ml.data.use.shuffle":"false","ml.block.size":"1000000","ml.model.type":"T_FLOAT_DENSE","ml.reg.l2":"0.0","ml.model.size":"148","ml.simpleinputlayer.matrix.output.format":"com.tencent.angel.model.output.format.ColIdValueTextRowFormat","graphJson":{"input":{"name":"input","type":"simpleinputlayer","outputdim":1,"transfunc":"identity","optimizer":{"type":"adam","reg2":0.01}},"simplelosslayer":{"name":"simplelosslayer","type":"simplelosslayer","lossfunc":"logloss","inputlayer":"input"}}}
19/04/18 11:06:08 INFO angel.AngelSavedModelBundle$ : before createMatrics: com.tencent.angel.ml.core.local.LocalModel@5b779c58
19/04/18 11:06:47 INFO angel.AngelSavedModelBundle$ : the graph file D:\prj\angel\serving-develop\serving-develop\models\angel\lr\lr-model\6\graph.json is not exist.
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at com.tencent.angel.ml.core.variable.Variable.create(Variable.scala:163)
	at com.tencent.angel.ml.core.local.LocalVariableManager$$anonfun$createALL$1.apply(LocalVariableManager.scala:12)
	at com.tencent.angel.ml.core.local.LocalVariableManager$$anonfun$createALL$1.apply(LocalVariableManager.scala:12)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.tencent.angel.ml.core.local.LocalVariableManager.createALL(LocalVariableManager.scala:12)
	at com.tencent.angel.ml.core.MLModel.createMatrices(MLModel.scala:89)
	at com.tencent.angel.serving.servables.angel.AngelSavedModelBundle$.create(AngelSavedModelBundle.scala:175)
	at com.tencent.angel.serving.servables.angel.AngelSourceAdapter$$anonfun$1.apply(AngelSourceAdapter.scala:18)
	at com.tencent.angel.serving.servables.angel.AngelSourceAdapter$$anonfun$1.apply(AngelSourceAdapter.scala:17)
	at com.tencent.angel.serving.core.SimpleLoader.load(SimpleLoader.scala:26)
	at com.tencent.angel.serving.core.LoaderHarness$$anonfun$1.apply$mcZ$sp(Servables.scala:99)
	at com.tencent.angel.serving.core.Retry.apply(Utils.scala:23)
	at com.tencent.angel.serving.core.LoaderHarness.load(Servables.scala:114)
	at com.tencent.angel.serving.core.BasicManager.executeLoad(BasicManager.scala:140)
	at com.tencent.angel.serving.core.BasicManager.executeLoadOrUnload(BasicManager.scala:133)
	at com.tencent.angel.serving.core.BasicManager.com$tencent$angel$serving$core$BasicManager$$handleLoadOrUnloadRequest(BasicManager.scala:88)
	at com.tencent.angel.serving.core.BasicManager$$anon$3.run(BasicManager.scala:69)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
6.the point is:
LOG.info(s"before createMatrics: "+model.toString)

      model.createMatrices(envCtx)

      LOG.info(s"start to load parameters for model")

**Comment by ouyangwen-it** [comment]
the reason: the graph file D:\prj\angel\serving-develop\serving-develop\models\angel\lr\lr-model\6\graph.json is not exist.
you should put the  generate graph.json in your model base path.

**Comment by mattxia** [comment]
this graph file exists, and we stepped into the project, and see that all the models share the same localvariablemanager,which we think is the problem, you can try that.

**Comment by mattxia** [comment]
> the reason: the graph file D:\prj\angel\serving-develop\serving-develop\models\angel\lr\lr-model\6\graph.json is not exist.
> you should put the generate graph.json in your model base path.

the assertion info is not accurate. the actual error comes from this part:
at com.tencent.angel.ml.core.local.LocalVariableManager.createALL(LocalVariableManager.scala:12)
at com.tencent.angel.ml.core.MLModel.createMatrices(MLModel.scala:89)
at

**Comment by ouyangwen-it** [comment]
bug fixed. now you should pull lasted code from angel's Serving branch, and then mvn install to local maven respository,  after this, repackage serving for test.

**Comment by mattxia** [comment]
> bug fixed. now you should pull lasted code from angel's Serving branch, and then mvn install to local maven respository, after this, repackage serving for test.

OK, I will try it ,thanks
