### ISSUE TITLE
Errors in  FtrlFMExample.scala 

### ISSUE THREAD

**Issue by syw2014** [Angel-ML/angel#735]
version: 2.1.0
platform: spark-on-angel
Error1:  There were no **opt.load** and **opt.save** function 
Error2:
java.io.NotSerializableException: com.tencent.angel.ml.feature.LabeledData
Serialization stack:
	- object not serializable (class: com.tencent.angel.ml.feature.LabeledData, value: com.tencent.angel.ml.feature.LabeledData@3a82bbce)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.SerializationStream.writeAll(Serializer.scala:141)
	at org.apache.spark.serializer.SerializerManager.dataSerializeStream(SerializerManager.scala:171)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1$$anonfun$apply$8.apply(BlockManager.scala:992)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1$$anonfun$apply$8.apply(BlockManager.scala:991)
	at org.apache.spark.storage.DiskStore.put(DiskStore.scala:57)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:991)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:948)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:888)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:948)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:694)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rachelsunrh** [comment]
maybe you can pull the new code again from  branch-2.1.0 , in which  there are functions, such as : save(path), saveWeight(path) and load(path). 
https://github.com/Angel-ML/angel/blob/branch-2.1.0/spark-on-angel/mllib/src/main/scala/com/tencent/angel/spark/ml/online_learning/FtrlFM.scala
