### ISSUE TITLE
multiple instances error for deepFM and WAD

### ISSUE THREAD

**Issue by mattxia** [Angel-ML/angel#740]
for deepfm and wad model, we found that
if the instance is like this: the first dim is bigger than the second one, it will 
{"instances": [{"sparseIndices":[1,2,3,4,5,6],"sparseValues":[1,1,1,1,1,1]},{"sparseIndices":[1,2,3,4,5,6,7,],"sparseValues":[1,1,1,1,1,1,1]}]}
it will return 
{
    "error": null
}

if the instance is like that :the first dim > second dim> third dim....
{"instances": [{"sparseIndices":[1,2,3,4,5,6,7,8],"sparseValues":[1,1,1,1,1,1,7,8]},{"sparseIndices":[1,2,3,4,5,6,7,],"sparseValues":[1,1,1,1,1,1,1]}]}
it will succeed
{
    "predictions": [
        {
            "trueLabel": "0.0",
            "proba": "0.9299815670886651",
            "pred": "2.5864062309265137",
            "attached": "NaN",
            "predLabel": "1.0",
            "sid": "0"
        },
        {
            "trueLabel": "0.0",
            "proba": "0.7169257756731272",
            "pred": "0.929263174533844",
            "attached": "NaN",
            "predLabel": "1.0",
            "sid": "1"
        }
    ]
}

what's wrong with it?thanks

**Comment by mattxia** [comment]
![image](https://user-images.githubusercontent.com/3146952/56705564-015fbf80-6744-11e9-95fb-abf8c9012782.png)

**Comment by mattxia** [comment]
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.tencent.angel.ml.math2.utils.MatrixUtils.rbCompDense2Blas(MatrixUtils.java:77)
	at com.tencent.angel.ml.core.network.layers.linear.FCLayer.doForward(FCLayer.scala:62)
	at com.tencent.angel.ml.core.network.layers.LinearLayer.forward(LinearLayer.scala:19)
	at com.tencent.angel.ml.core.network.layers.LinearLayer.forward(LinearLayer.scala:19)
	at com.tencent.angel.ml.core.network.layers.LinearLayer.forward(LinearLayer.scala:19)
	at com.tencent.angel.ml.core.network.layers.JoinLayer$$anonfun$2.apply(JoinLayer.scala:22)
	at com.tencent.angel.ml.core.network.layers.JoinLayer$$anonfun$2.apply(JoinLayer.scala:21)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.tencent.angel.ml.core.network.layers.JoinLayer.forward(JoinLayer.scala:21)
	at com.tencent.angel.ml.core.network.layers.LossLayer.forward(LossLayer.scala:30)
	at com.tencent.angel.ml.core.network.layers.LossLayer.predict(LossLayer.scala:19)
	at com.tencent.angel.ml.core.network.Graph.predict(Graph.scala:144)
	at com.tencent.angel.ml.core.local.LocalModel.predict(LocalModel.scala:29)
	at com.tencent.angel.serving.servables.angel.AngelSavedModelBundle.runPredict(AngelSavedModelBundle.scala:68)
	at com.tencent.angel.serving.servables.common.ServiceImpl$.predict(ServiceImpl.scala:41)
	at com.tencent.angel.serving.service.jersey.resources.HttpRestApiHandler.processPredictRequest(HttpRestApiHandler.scala:136)
	at com.tencent.angel.serving.service.jersey.resources.HttpRestApiHandler.processPredictionServiceRequest(HttpRestApiHandler.scala:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:427)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:984)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1045)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:236)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mattxia** [comment]
request is {"instances": [{"sparseIndices":[1,2,3,4,5],"sparseValues":[1,1,1,1,1]},{"sparseIndices":[1,2,3,4,5,6,7],"sparseValues":[1,1,1,1,1,1,1]}]}
in FCLayer:
middleCache = MatrixUtils.rbCompDense2Blas(mat)
        subDim = mat.getSubDim
calculate the dim with the first array length ,we got dim is 40
and in System.arraycopy(src, 0, data, rowId * dim + partId * subDim, src.length);
cause **ArrayIndexOutOfBoundsException**

19/04/25 22:27:43 INFO linear.FCLayer : layer is :fclayer_0, matrix: com.tencent.angel.ml.math2.matrix.RBCompIntFloatMatrix@a38fa31
19/04/25 22:27:43 INFO linear.FCLayer : matrix is 8, Rows:2
19/04/25 22:27:44 INFO MatrixUtils : rows: 5
19/04/25 22:27:44 INFO MatrixUtils : rowId: 0, dim: 40,partId:0,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 0, dim: 40,partId:1,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 0, dim: 40,partId:2,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 0, dim: 40,partId:3,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 0, dim: 40,partId:4,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rows: 7
19/04/25 22:27:44 INFO MatrixUtils : rowId: 1, dim: 40,partId:0,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 1, dim: 40,partId:1,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 1, dim: 40,partId:2,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 1, dim: 40,partId:3,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 1, dim: 40,partId:4,subDim: 8
19/04/25 22:27:44 INFO MatrixUtils : rowId: 1, dim: 40,partId:5,subDim: 8


If the request is {{"sparseIndices":[1,2,3,4,5,6,7],"sparseValues":[1,1,1,1,1,1,1]},"instances": [{"sparseIndices":[1,2,3,4,5],"sparseValues":[1,1,1,1,1]}]}
the dim will be 56 
9/04/25 22:26:50 INFO MatrixUtils : rows: 7
19/04/25 22:26:50 INFO MatrixUtils : rowId: 0, dim: 56,partId:0,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 0, dim: 56,partId:1,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 0, dim: 56,partId:2,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 0, dim: 56,partId:3,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 0, dim: 56,partId:4,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 0, dim: 56,partId:5,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 0, dim: 56,partId:6,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rows: 5
19/04/25 22:26:50 INFO MatrixUtils : rowId: 1, dim: 56,partId:0,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 1, dim: 56,partId:1,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 1, dim: 56,partId:2,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 1, dim: 56,partId:3,subDim: 8
19/04/25 22:26:50 INFO MatrixUtils : rowId: 1, dim: 56,partId:4,subDim: 8

**Comment by rachelsunrh** [comment]
this usage of multiple instances is not correct, the number of index in each instance must be same while in multiple instances

**Comment by rachelsunrh** [comment]
this usage of multiple instances is not correct, the number of indices in each instance must be same while in multiple instances
