### ISSUE TITLE
angel-submit是否有配置项，可以让任务每次跑的时候，overwrite覆盖log和model路径

### ISSUE THREAD

**Issue by wqh17101** [Angel-ML/angel#756]

**Comment by paynie** [comment]
angel.output.path.deleteonexist=true

**Comment by wqh17101** [comment]
```
19/05/06 11:20:40 ERROR utils.AngelRunJar: submit job failed 
com.tencent.angel.exception.InvalidParameterException: there is no value for parameter angel.output.path.deleteonexist=true
        at com.tencent.angel.utils.ConfUtils.parseArgs(ConfUtils.java:134)
        at com.tencent.angel.utils.ConfUtils.initConf(ConfUtils.java:44)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:44)
```
脚本如下
```
 sh ./angel-submit \
         --angel.app.submit.class com.tencent.angel.ml.core.graphsubmit.GraphRunner \
        --angel.train.data.path "hdfs://jr-hdfs/tmp/wangqinghua/lda/angel_test/data/a9a_123d_train.libsvm" \
        --angel.log.path "hdfs://jr-hdfs/tmp/wangqinghua/lda/angel_test/log" \
        --angel.save.model.path "hdfs://jr-hdfs/tmp/wangqinghua/lda/angel_test/model" \
        --action.type train \
        --ml.model.class.name com.tencent.angel.ml.classification.LogisticRegression \
        --ml.epoch.num 10 \
        --ml.data.type libsvm \
        --ml.feature.index.range 1024 \
        --angel.job.name LR_test \
        --angel.am.memory.gb 2 \
        --angel.worker.memory.gb 2 \
        --angel.ps.memory.gb 2 \
        --angel.staging.dir "hdfs://jr-hdfs//tmp/wangqinghua/lda/angel_test/stage" \
        --angel.output.path.deleteonexist=true
```

**Comment by wqh17101** [comment]
OMG
源码里这是一个string不是Boolean
```     
public static final String ANGEL_JOB_OUTPUT_PATH_DELETEONEXIST = "angel.output.path.deleteonexist";
```
不能用
angel.output.path.deleteonexist=true，要用angel.output.path.deleteonexist true

**Comment by maozida880** [comment]
-Dangel.output.path.deleteonexist=true
OR
--angel.output.path.deleteonexist true
Both of them are OK

**Comment by maozida880** [comment]
graphsubmit.GraphRunner
模式下无法读取graph.json文件
