### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3

### ISSUE THREAD

**Issue by pengteng** [Angel-ML/angel#816]
您好，我在angle进程上日志报错 ：
LogType:stderr
Log Upload Time:Fri Aug 02 14:21:45 +0800 2019
LogLength:1932
Log Contents:
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=100M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=200M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
Java HotSpot(TM) 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
Java HotSpot(TM) 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at com.tencent.angel.protobuf.ProtobufUtil.convertToIdProto(ProtobufUtil.java:138)
at com.tencent.angel.ps.ParameterServer.(ParameterServer.java:221)
at com.tencent.angel.ps.ParameterServer.main(ParameterServer.java:360)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.GeneratedMessageV3
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

查看https://github.com/google/safe-html-types/issues/1 问题，要protoc更新为3.1*会解决问题，请问有碰到过类似问题吗

**Comment by pengteng** [comment]
本地local运行无问题

**Comment by pengteng** [comment]
解决问题，如下添加jar 
![image](https://user-images.githubusercontent.com/10191279/62363148-348ac980-b551-11e9-814f-b12c7fe2ddbd.png)
