### ISSUE TITLE
test LR demo by run angel_submit.sh failed, ClassNotFoundException

### ISSUE THREAD

**Issue by XuSShuai** [Angel-ML/angel#848]
run command:
------
  ./angel-submit \
          --angel.app.submit.class com.tencent.angel.ml.core.graphsubmit.GraphRunner \
      --angel.train.data.path "hdfs://my-nn:54310/test/lr_data" \
      --angel.log.path "hdfs://my-nn:54310/test/log" \
      --angel.save.model.path "hdfs://my-nn:54310/test/model" \
      --action.type train \
      --ml.model.class.name com.tencent.angel.ml.classification.LogisticRegression \
      --ml.epoch.num 10 \
      --ml.data.type libsvm \
      --ml.feature.index.range 1024 \
      --angel.job.name LR_test \
      --angel.am.memory.gb 2 \
      --angel.worker.memory.gb 2 \
      --angel.ps.memory.gb 2

error log:
------
19/08/21 11:49:16 FATAL utils.AngelRunJar: load submit class failed com.tencent.angel.ml.core.graphsubmit.GraphRunner
java.lang.ClassNotFoundException: com.tencent.angel.ml.core.graphsubmit.GraphRunner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:58)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:54)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1700)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:54)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:38)
19/08/21 11:49:16 FATAL utils.AngelRunJar: submit job failed 
java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1715)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:54)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:38)
Caused by: com.tencent.angel.exception.InvalidParameterException: load submit class failed com.tencent.angel.ml.core.graphsubmit.GraphRunner
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:64)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:54)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1700)
	... 2 more

anyone know how to fix it? thanks in advance.

**Comment by paynie** [comment]
Which version are you using?

**Comment by XuSShuai** [comment]
> Which version are you using?

angel-1.4.0

**Comment by paynie** [comment]
GraphRunner is definded in 2.X， you can update the version to 2.3.0

**Comment by Brentbin** [comment]
Is that demo work in angel-3.0.0 fine?
@paynie

**Comment by XuSShuai** [comment]
> GraphRunner is definded in 2.X， you can update the version to 2.3.0

thanks for your reply.
