### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration

### ISSUE THREAD

**Issue by krisjin** [Angel-ML/angel#856]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration
	at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.<init>(DefaultMetricsSystem.java:38)
	at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.<clinit>(DefaultMetricsSystem.java:36)
	at org.apache.hadoop.security.UserGroupInformation$UgiMetrics.create(UserGroupInformation.java:121)
	at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:237)
	at com.tencent.angel.utils.UGITools.getCurrentUser(UGITools.java:43)
	at com.tencent.angel.client.AngelClient.setUser(AngelClient.java:996)
	at com.tencent.angel.client.local.AngelLocalClient.startPSServer(AngelLocalClient.java:124)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:48)
	at com.tencent.angel.example.ml.LogisticRegLocalExample.train(LogisticRegLocalExample.java:156)
	at com.tencent.angel.example.ml.LogisticRegLocalExample.main(LogisticRegLocalExample.java:201)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

**Comment by krisjin** [comment]
<dependency>
            <groupId>commons-configuration</groupId>
            <artifactId>commons-configuration</artifactId>
            <version>1.10</version>
        </dependency>
