### ISSUE TITLE
缺少方法：com.tencent.angel.mlcore.utils.JsonUtils$.toJsonConfStr

### ISSUE THREAD

**Issue by wjlight** [Angel-ML/angel#873]
分支：branch-3.0.1-hadoop3
提交命令：

> ./angel-submit \
         --angel.app.submit.class com.tencent.angel.ml.core.graphsubmit.GraphRunner \
        --angel.train.data.path "hdfs://localhost:9000/test/lr_data" \
        --angel.log.path "hdfs://localhost:9000/test/log" \
        --angel.save.model.path "hdfs://localhost:9000/test/model" \
        --action.type train \
        --ml.model.class.name com.tencent.angel.ml.classification.LogisticRegression \
        --ml.epoch.num 10 \
        --ml.data.type libsvm \
        --ml.feature.index.range 1024 \
        --angel.job.name LR_test \
        --angel.am.memory.gb 2 \
        --angel.worker.memory.gb 2 \
        --angel.ps.memory.gb 2

最后一步出现：

> 2019-09-27 07:25:46,126 INFO client.AngelClient: Epoch: 0. Metrics={}
2019-09-27 07:25:54,137 INFO client.AngelClient: Epoch: 1. Metrics={"train.loss":0.406998,"validate.loss":0.394514}
2019-09-27 07:25:58,142 INFO client.AngelClient: Epoch: 2. Metrics={"train.loss":0.361025,"validate.loss":0.377118}
2019-09-27 07:26:02,147 INFO client.AngelClient: Epoch: 3. Metrics={"train.loss":0.336801,"validate.loss":0.355947}
2019-09-27 07:26:06,152 INFO client.AngelClient: Epoch: 4. Metrics={"train.loss":0.330747,"validate.loss":0.351856}
2019-09-27 07:26:10,157 INFO client.AngelClient: Epoch: 5. Metrics={"train.loss":0.329211,"validate.loss":0.348767}
2019-09-27 07:26:14,161 INFO client.AngelClient: Epoch: 6. Metrics={"train.loss":0.328655,"validate.loss":0.347220}
2019-09-27 07:26:18,166 INFO client.AngelClient: Epoch: 7. Metrics={"train.loss":0.328825,"validate.loss":0.346512}
2019-09-27 07:26:23,172 INFO client.AngelClient: Epoch: 8. Metrics={"train.loss":0.328975,"validate.loss":0.345847}
2019-09-27 07:26:27,177 INFO client.AngelClient: Epoch: 9. Metrics={"train.loss":0.328995,"validate.loss":0.345319}
2019-09-27 07:26:31,182 INFO client.AngelClient: Epoch: 10. Metrics={"train.loss":0.328991,"validate.loss":0.344968}
2019-09-27 07:26:31,182 INFO client.AngelClient: job is finished! status: J_EXECUTE_SUCCESSED
2019-09-27 07:26:31,182 INFO client.AngelClient: action type train
2019-09-27 07:26:37,230 INFO client.AngelClient: stop the application
2019-09-27 07:26:37,230 INFO client.AngelClient: master is not null, send stop command to Master, stateCode=0
Exception in thread "main" java.lang.NoSuchMethodError: com.tencent.angel.mlcore.utils.JsonUtils$.toJsonConfStr(Lcom/tencent/angel/mlcore/conf
/SharedConf;Lcom/tencent/angel/mlcore/network/Graph;)Ljava/lang/String;
        at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:71)
        at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:45)
        at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:31)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:91)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:77)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
        at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:77)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:44)

angel-mlcore包缺少toJsonConfStr方法

**Comment by ouyangwen-it** [comment]
> 分支：branch-3.0.1-hadoop3
> 提交命令：
> 
> > ./angel-submit 
> >          --angel.app.submit.class com.tencent.angel.ml.core.graphsubmit.GraphRunner 
> >         --angel.train.data.path "hdfs://localhost:9000/test/lr_data" 
> >         --angel.log.path "hdfs://localhost:9000/test/log" 
> >         --angel.save.model.path "hdfs://localhost:9000/test/model" 
> >         --action.type train 
> >         --ml.model.class.name com.tencent.angel.ml.classification.LogisticRegression 
> >         --ml.epoch.num 10 
> >         --ml.data.type libsvm 
> >         --ml.feature.index.range 1024 
> >         --angel.job.name LR_test 
> >         --angel.am.memory.gb 2 
> >         --angel.worker.memory.gb 2 
> >         --angel.ps.memory.gb 2
> 
> 最后一步出现：
> 
> > 2019-09-27 07:25:46,126 INFO client.AngelClient: Epoch: 0. Metrics={}
> > 2019-09-27 07:25:54,137 INFO client.AngelClient: Epoch: 1. Metrics={"train.loss":0.406998,"validate.loss":0.394514}
> > 2019-09-27 07:25:58,142 INFO client.AngelClient: Epoch: 2. Metrics={"train.loss":0.361025,"validate.loss":0.377118}
> > 2019-09-27 07:26:02,147 INFO client.AngelClient: Epoch: 3. Metrics={"train.loss":0.336801,"validate.loss":0.355947}
> > 2019-09-27 07:26:06,152 INFO client.AngelClient: Epoch: 4. Metrics={"train.loss":0.330747,"validate.loss":0.351856}
> > 2019-09-27 07:26:10,157 INFO client.AngelClient: Epoch: 5. Metrics={"train.loss":0.329211,"validate.loss":0.348767}
> > 2019-09-27 07:26:14,161 INFO client.AngelClient: Epoch: 6. Metrics={"train.loss":0.328655,"validate.loss":0.347220}
> > 2019-09-27 07:26:18,166 INFO client.AngelClient: Epoch: 7. Metrics={"train.loss":0.328825,"validate.loss":0.346512}
> > 2019-09-27 07:26:23,172 INFO client.AngelClient: Epoch: 8. Metrics={"train.loss":0.328975,"validate.loss":0.345847}
> > 2019-09-27 07:26:27,177 INFO client.AngelClient: Epoch: 9. Metrics={"train.loss":0.328995,"validate.loss":0.345319}
> > 2019-09-27 07:26:31,182 INFO client.AngelClient: Epoch: 10. Metrics={"train.loss":0.328991,"validate.loss":0.344968}
> > 2019-09-27 07:26:31,182 INFO client.AngelClient: job is finished! status: J_EXECUTE_SUCCESSED
> > 2019-09-27 07:26:31,182 INFO client.AngelClient: action type train
> > 2019-09-27 07:26:37,230 INFO client.AngelClient: stop the application
> > 2019-09-27 07:26:37,230 INFO client.AngelClient: master is not null, send stop command to Master, stateCode=0
> > Exception in thread "main" java.lang.NoSuchMethodError: com.tencent.angel.mlcore.utils.JsonUtils$.toJsonConfStr(Lcom/tencent/angel/mlcore/conf
> > /SharedConf;Lcom/tencent/angel/mlcore/network/Graph;)Ljava/lang/String;
> > at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:71)
> > at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:45)
> > at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:31)
> > at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:91)
> > at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:77)
> > at java.security.AccessController.doPrivileged(Native Method)
> > at javax.security.auth.Subject.doAs(Subject.java:422)
> > at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
> > at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:77)
> > at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:44)

branch-3.0.1-hadoop3 needs angel-mlcore 0.1.2, you can change  angel-mlcore jar version in angel-site.xml in conf dir, or pull the latest branch-3.0.1-hadoop3.

**Comment by wjlight** [comment]
@ouyangwen-it 谢谢，但是angel-mlcore 0.1.2里面也没有toJsonConfStr这方法
