### ISSUE TITLE
Permission denied: user=yarn, access=WRITE when saving the trained model to hdfs

### ISSUE THREAD

**Issue by matricer** [Angel-ML/angel#881]
Package: Angel-3.0.0
Problem: permission denied: user=yarn, access=WRITE when training was finished and started to save the trained model to hdfs. How should I use my own user account rather than user "yarn" ?

19/10/29 20:23:09 ERROR utils.AngelRunJar: submit job failed 
com.tencent.angel.exception.AngelException: Model save falied org.apache.hadoop.security.AccessControlException: org.apache.hadoop.security.AccessControlException: Permission denied: user=yarn, access=WRITE, inode="model":XXXXXXXXXX:XXXXXXXXXX:rwxr-xr-x
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:96)
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:58)
	at org.apache.hadoop.hdfs.DFSClient.rename(DFSClient.java:1361)
	at org.apache.hadoop.hdfs.DistributedFileSystem.rename(DistributedFileSystem.java:788)
	at org.apache.hadoop.fs.viewfs.ViewFs.rename(ViewFs.java:210)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.qihoo.spinner.HYReflection.invoke(HYReflection.java:130)
	at net.qihoo.spinner.SpinnerDistributedFileSystem.rename(SpinnerDistributedFileSystem.java:383)
	at com.tencent.angel.utils.HdfsUtil.rename(HdfsUtil.java:378)
	at com.tencent.angel.master.matrix.committer.AMModelSaver.finalCommit(AMModelSaver.java:968)
	at com.tencent.angel.master.matrix.committer.AMModelSaver.access$1100(AMModelSaver.java:68)
	at com.tencent.angel.master.matrix.committer.AMModelSaver$3.run(AMModelSaver.java:866)
	at java.lang.Thread.run(Thread.java:745)

**Comment by JiangWei** [comment]
@matricer have you solved this problem yet? i run into same issue
