### ISSUE TITLE
The operation is not supported!

### ISSUE THREAD

**Issue by douglasren** [Angel-ML/angel#883]
---
name:Feature request
about: 0.3 in stage 4.0 (TID 13, c1-dsj-hadoop003.bj, executor 433): com.tencent.angel.exception.AngelException: The operation is not supported!
at com.tencent.angel.ml.math2.vector.Vector.imul(Vector.java:94)
at com.tencent.angel.spark.ml.online_learning.FtrlFM.delta(FtrlFM.scala:194)
at com.tencent.angel.spark.ml.online_learning.FtrlFM.optimize(FtrlFM.scala:169)
at com.inke.streaming.service.live.offline.ffm.AngelFmFtrlTestApp$$anonfun$train$1$$anonfun$24$$anonfun$25.apply(AngelFmFtrlTestApp.scala:171)
at com.inke.streaming.service.live.offline.ffm.AngelFmFtrlTestApp$$anonfun$train$1$$anonfun$24$$anonfun$25.apply(AngelFmFtrlTestApp.scala:171)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
at scala.collection.Iterator$class.foreach(Iterator.scala:893)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
at scala.collection.TraversableOnce$class.sum(TraversableOnce.scala:216)
at scala.collection.AbstractIterator.sum(Iterator.scala:1336)
at com.inke.streaming.service.live.offline.ffm.AngelFmFtrlTestApp$$anonfun$train$1$$anonfun$24.apply(AngelFmFtrlTestApp.scala:171)
at com.inke.streaming.service.live.offline.ffm.AngelFmFtrlTestApp$$anonfun$train$1$$anonfun$24.apply(AngelFmFtrlTestApp.scala:167)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
at org.apache.spark.scheduler.Task.run(Task.scala:99)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
title: ''
label: bug/enhancement/question
assignees: ''
---

**Environment**:
- Java version: 1.8
- Scala version: 2.11
- Spark version:2.1.0
- PyTorch and Python version:
- OS and version: centos 6.5
- angel version:2.3.1

FtrlFMExample不能运行，原因是基础的数据库不支持这样的操作
  public Vector imul(Vector other) {
    throw new AngelException("The operation is not supported!");
  }
看了下最新的版本还是不支持稀疏向量的操作，这个有更新的计划吗

**Comment by douglasren** [comment]
It has been solved. The code has been submitted to https://github.com/douglasren/angel/tree/branch-2.3.1 .
