### ISSUE TITLE
I met a problem:java.io.FileNotFoundException: /tmp  300     at org.apache.hadoop.fs.viewfs.InodeTree.resolve(InodeTree.java:402)  301     at org.apache.hadoop.fs.viewfs.ViewFileSystem.mkdirs(ViewFileSystem.java:449)

### ISSUE THREAD

**Issue by zrfan** [Angel-ML/angel#893]
---
name: Bug report/Feature request/Question
about: Create a report to help us improve
title: ''
label: bug/enhancement/question
assignees: ''
---

**Environment**:
- Java version: 1.8
- Scala version:2.11
- Spark version:2.21
- PyTorch and Python version:
- OS and version: linux

19/11/27 18:58:05 INFO YarnClusterSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached      minRegisteredResourcesRatio: 0.8
 286 19/11/27 18:58:05 INFO YarnClusterScheduler: YarnClusterScheduler.postStartHook done
 287 19/11/27 18:58:05 INFO BlockManagerMasterEndpoint: Registering block manager xyz1166.hadoop.data.sina.com.cn:40197        with 2.2 GB RAM, BlockManagerId(6, xyz1166.hadoop.data.sina.com.cn, 40197, None)
 19/11/27 18:58:05 INFO BlockManagerMasterEndpoint: Registering block manager xyz1166.hadoop.data.sina.com.cn:45822        with 2.2 GB RAM, BlockManagerId(5, xyz1166.hadoop.data.sina.com.cn, 45822, None)
 19/11/27 18:58:05 INFO AngelPSClient: userResourceFiles=viewfs://c9/user_ext/weibo_bigdata_push/.sparkStaging/            application_1563433337431_24320530/lr.json,viewfs://c9/user_ext/weibo_bigdata_push/.sparkStaging/                         application_1563433337431_24320530/hive-site.xml
 19/11/27 18:58:05 INFO UGITools: UGI_PROPERTY_NAME is null
 19/11/27 18:58:06 INFO AngelClient: running mode = ANGEL_PS
 19/11/27 18:58:06 INFO AngelClient: Make dir for model output parent path: file:/tmp/spark-on-angel
 19/11/27 18:58:06 INFO HdfsUtil: tmp output dir is file:///tmp/weibo_bigdata_push/                                        application_1563433337431_24320662_969940c1-276b-467c-8e15-027043aba8aa
19/11/27 18:58:06 INFO HdfsUtil: tmp output dir is file:///tmp/weibo_bigdata_push/                                        application_1563433337431_24320662_08f3699b-7c8c-4e14-96b1-b82543c3019e
 19/11/27 18:58:06 INFO AngelClient: angel.tmp.output.path=file:/tmp/weibo_bigdata_push/                                   application_1563433337431_24320662_969940c1-276b-467c-8e15-027043aba8aa
 19/11/27 18:58:06 INFO AngelClient: internal state file is file:/tmp/weibo_bigdata_push/                                  application_1563433337431_24320662_08f3699b-7c8c-4e14-96b1-b82543c3019e/state
 19/11/27 18:58:06 INFO AngelYarnClient: default FileSystem: viewfs://c9/
  19/11/27 18:58:06 ERROR AngelYarnClient: submit application to yarn failed.
 java.io.FileNotFoundException: /tmp
      at org.apache.hadoop.fs.viewfs.InodeTree.resolve(InodeTree.java:402)
      at org.apache.hadoop.fs.viewfs.ViewFileSystem.mkdirs(ViewFileSystem.java:449)
      at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:1881)
      at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:600)
      at com.tencent.angel.client.yarn.AngelYarnClient.copyAndConfigureFiles(AngelYarnClient.java:208)
      at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:153)
      at com.tencent.angel.client.AngelPSClient.startPS(AngelPSClient.java:115)
      at com.tencent.angel.spark.context.AngelPSContext$.launchAngel(AngelPSContext.scala:327)
      at com.tencent.angel.spark.context.AngelPSContext$.apply(AngelPSContext.scala:282)
      at com.tencent.angel.sona.context.PSContext$.liftedTree1$1(PSContext.scala:98)
      at com.tencent.angel.sona.context.PSContext$.instance(PSContext.scala:96)
     at com.tencent.angel.sona.context.PSContext$.getOrCreate(PSContext.scala:80)
      at com.sina.weibo.dsp.SonaTest$.main(SonaTest.scala:20)
      at com.sina.weibo.dsp.SonaTest.main(SonaTest.scala)

**Comment by zrfan** [comment]
![image](https://user-images.githubusercontent.com/4252380/69719317-31909600-114b-11ea-94bd-fad7a893871b.png)

**Comment by ouyangwen-it** [comment]
跑的是哪个版本的angel，哪个算法呢，请检查hdfs集群是否部署正确
