### ISSUE TITLE
本地任务失败./angel-example com.tencent.angel.example.ml.DeepFMLocalExample

### ISSUE THREAD

**Issue by flytoylf** [Angel-ML/angel#902]
本地执行./angel-example com.tencent.angel.example.ml.DeepFMLocalExample失败
日志如下：
19/12/06 21:45:10 INFO master.AngelApplicationMaster : write app state over
19/12/06 21:45:10 WARN master.AngelApplicationMaster : App Staging directory is null
19/12/06 21:45:10 INFO master.AngelApplicationMaster : Deleting tmp output directory file:/tmp/work/application_1575639909105_1859751923_ad9a6590-c370-42eb-9a89-075e8681a0f7
19/12/06 21:45:20 INFO ipc.NettyServer : Stopping server on 24341
19/12/06 21:45:20 INFO master.MasterService : WorkerPSService is stoped!
19/12/06 21:45:20 INFO master.AngelApplicationMaster : Exiting Angel AppMaster..GoodBye!
19/12/06 21:45:20 WARN localcluster.LocalResourceManager : event handler is interrupted
19/12/06 21:45:22 INFO localcluster.LocalCluster : =============================================stop cluster over=======================================
19/12/06 21:45:22 ERROR ml.DeepFMLocalExample : run DeepFMLocalExample:train failed.
java.lang.NullPointerException
	at com.tencent.angel.mlcore.utils.JsonUtils$.layerFromJson(JsonUtils.scala:144)
	at com.tencent.angel.mlcore.utils.JsonUtils$.layerFromJson(JsonUtils.scala:136)
	at com.tencent.angel.ml.core.graphsubmit.AngelModel.buildNetwork(AngelModel.scala:54)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:53)
	at com.tencent.angel.example.ml.DeepFMLocalExample.train(DeepFMLocalExample.java:125)
	at com.tencent.angel.example.ml.DeepFMLocalExample.main(DeepFMLocalExample.java:170)
Exception in thread "main" java.lang.NullPointerException
	at com.tencent.angel.mlcore.utils.JsonUtils$.layerFromJson(JsonUtils.scala:144)
	at com.tencent.angel.mlcore.utils.JsonUtils$.layerFromJson(JsonUtils.scala:136)
	at com.tencent.angel.ml.core.graphsubmit.AngelModel.buildNetwork(AngelModel.scala:54)
	at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:53)
	at com.tencent.angel.example.ml.DeepFMLocalExample.train(DeepFMLocalExample.java:125)
	at com.tencent.angel.example.ml.DeepFMLocalExample.main(DeepFMLocalExample.java:170)

**Comment by flytoylf** [comment]
同样命令执行LR和FM是成功的

**Comment by ouyangwen-it** [comment]
请问用的是哪个版本angel，什么数据集做的测试呢
