### ISSUE TITLE
DeepFM java.lang.ArrayIndexOutOfBoundsException: 13

### ISSUE THREAD

**Issue by wjlight** [Angel-ML/angel#909]
sona0.1.0
Angel3.0.1

error log：
```
20/01/03 16:45:26 WARN TaskSetManager: Lost task 0.0 in stage 4.0 (TID 4, bj6-p-gryai-graph-spark03.ps.wps.cn, executor 1): java.lang.ArrayIndexOutOfBoundsException: 13
	at com.tencent.angel.mlcore.network.layers.Layer$$anonfun$gatherGradInput$1$$anonfun$apply$2$$anonfun$apply$mcVI$sp$2.apply(Layer.scala:134)
	at com.tencent.angel.mlcore.network.layers.Layer$$anonfun$gatherGradInput$1$$anonfun$apply$2$$anonfun$apply$mcVI$sp$2.apply(Layer.scala:133)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at com.tencent.angel.mlcore.network.layers.Layer$$anonfun$gatherGradInput$1$$anonfun$apply$2.apply$mcVI$sp(Layer.scala:133)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.tencent.angel.mlcore.network.layers.Layer$$anonfun$gatherGradInput$1.apply(Layer.scala:129)
	at com.tencent.angel.mlcore.network.layers.Layer$$anonfun$gatherGradInput$1.apply(Layer.scala:111)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.tencent.angel.mlcore.network.layers.Layer.gatherGradInput(Layer.scala:111)
	at com.tencent.angel.mlcore.network.layers.InputLayer.backward(InputLayer.scala:43)
	at com.tencent.angel.mlcore.network.Graph$$anonfun$calBackward$1.apply(Graph.scala:160)
	at com.tencent.angel.mlcore.network.Graph$$anonfun$calBackward$1.apply(Graph.scala:160)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at com.tencent.angel.mlcore.network.Graph.calBackward(Graph.scala:160)
	at com.tencent.angel.sona.ml.common.Trainer.trainOneBatch(Trainer.scala:67)
	at com.tencent.angel.sona.ml.classification.AngelClassifier$$anonfun$train$1$$anonfun$apply$mcVI$sp$1$$anonfun$8.apply(AngelClassifier.scala:246)
	at com.tencent.angel.sona.ml.classification.AngelClassifier$$anonfun$train$1$$anonfun$apply$mcVI$sp$1$$anonfun$8.apply(AngelClassifier.scala:246)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:185)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$14.apply(RDD.scala:1021)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$14.apply(RDD.scala:1019)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2130)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2130)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
deepfm.json
```
{
  "data": {
    "format": "libsvm",
    "indexrange": 2218,
    "numfield": 13,
    "validateratio": 0.1,
    "sampleratio": 0.2
  },
  "model": {
    "modeltype": "T_DOUBLE_SPARSE_LONGKEY",
    "modelsize": 2218
  },
  "train": {
    "epoch": 5,
    "numupdateperepoch": 5,
    "lr": 0.5,
    "decayclass": "StandardDecay",
    "decayalpha": 0.01
  },
  "default_optimizer": "Momentum",
  "layers": [
    {
      "name": "wide",
      "type": "simpleinputlayer",
      "outputdim": 1,
      "transfunc": "identity"
    },
    {
      "name": "embedding",
      "type": "embedding",
      "numfactors": 8,
      "outputdim": 109,
      "optimizer": {
        "type": "momentum",
        "momentum": 0.9,
        "reg2": 0.01
      }
    },
    {
      "name": "fclayer",
      "type": "FCLayer",
      "outputdims": [
        100,
        100,
        1
      ],
      "transfuncs": [
        "relu",
        "relu",
        "identity"
      ],
      "inputlayer": "embedding"
    },
    {
      "name": "biinnersumcross",
      "type": "BiInnerSumCross",
      "inputlayer": "embedding",
      "outputdim": 1
    },
    {
      "name": "sumPooling",
      "type": "SumPooling",
      "outputdim": 1,
      "inputlayers": [
        "wide",
        "biinnersumcross",
        "fclayer"
      ]
    },
    {
      "name": "simplelosslayer",
      "type": "simplelosslayer",
      "lossfunc": "logloss",
      "inputlayer": "sumPooling"
    }
  ]
}
```
train data e.g.
```
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 535:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 1650:1.0
1.0 1:1.0 6:1.0 14:1.0 19:1.0 198:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1313:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 198:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1313:1.0
-1.0 1:1.0 8:1.0 16:1.0 19:1.0 703:1.0 1105:1.0 1109:1.0 1114:1.0 1122:1.0 1125:1.0 1129:1.0 1134:1.0 1818:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 198:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1313:1.0
-1.0 3:1.0 7:1.0 13:1.0 19:1.0 728:1.0 1107:1.0 1110:1.0 1116:1.0 1119:1.0 1127:1.0 1130:1.0 1134:1.0 1843:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 957:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 2072:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 760:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 1875:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 691:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1806:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 789:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 1904:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 484:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 1599:1.0
-1.0 3:1.0 7:1.0 13:1.0 19:1.0 882:1.0 1107:1.0 1110:1.0 1116:1.0 1119:1.0 1127:1.0 1130:1.0 1134:1.0 1997:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 762:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 1877:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 469:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 1584:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 1085:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 2200:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 198:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1313:1.0
-1.0 1:1.0 8:1.0 16:1.0 19:1.0 894:1.0 1105:1.0 1109:1.0 1114:1.0 1122:1.0 1125:1.0 1129:1.0 1134:1.0 2009:1.0
-1.0 1:1.0 8:1.0 16:1.0 19:1.0 513:1.0 1105:1.0 1109:1.0 1114:1.0 1122:1.0 1125:1.0 1129:1.0 1134:1.0 1628:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 883:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 1998:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 285:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1400:1.0
-1.0 2:1.0 8:1.0 15:1.0 19:1.0 490:1.0 1106:1.0 1109:1.0 1115:1.0 1121:1.0 1126:1.0 1129:1.0 1134:1.0 1605:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 285:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1400:1.0
-1.0 2:1.0 7:1.0 13:1.0 19:1.0 705:1.0 1106:1.0 1109:1.0 1115:1.0 1119:1.0 1126:1.0 1129:1.0 1134:1.0 1820:1.0
-1.0 2:1.0 7:1.0 13:1.0 19:1.0 1025:1.0 1106:1.0 1109:1.0 1115:1.0 1119:1.0 1126:1.0 1129:1.0 1134:1.0 2140:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 33:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1148:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 33:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1148:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 33:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1148:1.0
1.0 1:1.0 6:1.0 14:1.0 19:1.0 33:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1148:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 33:1.0 1105:1.0 1109:1.0 1114:1.0 1120:1.0 1125:1.0 1129:1.0 1134:1.0 1148:1.0
```

**Comment by wjlight** [comment]
```
{
      "name": "embedding",
      "type": "embedding",
      "numfactors": 8,
      "outputdim": 109,
      "optimizer": {
        "type": "momentum",
        "momentum": 0.9,
        "reg2": 0.01
      }
    },
```
outputdim /  numfactors = numFeature
