### ISSUE TITLE
deep&wide feature number if not equal 13,will error

### ISSUE THREAD

**Issue by wjlight** [Angel-ML/angel#910]
sona0.1.0
angel3.0.1

If my train data has not 13 number of features, will have error below:
error log:
```
20/01/04 21:03:06 ERROR MatrixTransportClient: serialize request PutPartitionUpdateRequest [taskIndex=-1, rowsSplit size=0, updateClock=false, toString()=PartitionRequest{clock=-1, partKey=PartitionKey(matrixId=2, partitionId=4, startRow=0, startCol=8320, endRow=3, endCol=10400)indexNum=-1), comeFromPs=false} com.tencent.angel.ps.server.data.request.UpdateRequest@24] failed 
java.lang.ArrayIndexOutOfBoundsException: 8320
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serializeIntDoubleRow(RowsViewUpdateItem.java:822)
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serializeRow(RowsViewUpdateItem.java:499)
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serialize(RowsViewUpdateItem.java:70)
	at com.tencent.angel.ps.server.data.request.UpdateRequest.serialize(UpdateRequest.java:127)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient.serializeRequest(MatrixTransportClient.java:2150)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient.access$3300(MatrixTransportClient.java:123)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Requester.sendRequest(MatrixTransportClient.java:2033)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Requester.run(MatrixTransportClient.java:1943)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20/01/04 21:03:06 ERROR MatrixTransportClient: serialize request PutPartitionUpdateRequest [taskIndex=-1, rowsSplit size=0, updateClock=false, toString()=PartitionRequest{clock=-1, partKey=PartitionKey(matrixId=2, partitionId=2, startRow=0, startCol=4160, endRow=3, endCol=6240)indexNum=-1), comeFromPs=false} com.tencent.angel.ps.server.data.request.UpdateRequest@22] failed 
java.lang.ArrayIndexOutOfBoundsException: 5600
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serializeIntDoubleRow(RowsViewUpdateItem.java:822)
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serializeRow(RowsViewUpdateItem.java:499)
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serialize(RowsViewUpdateItem.java:70)
	at com.tencent.angel.ps.server.data.request.UpdateRequest.serialize(UpdateRequest.java:127)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient.serializeRequest(MatrixTransportClient.java:2150)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient.access$3300(MatrixTransportClient.java:123)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Requester.sendRequest(MatrixTransportClient.java:2033)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Requester.run(MatrixTransportClient.java:1943)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20/01/04 21:03:06 ERROR MatrixTransportClient: serialize request PutPartitionUpdateRequest [taskIndex=-1, rowsSplit size=0, updateClock=false, toString()=PartitionRequest{clock=-1, partKey=PartitionKey(matrixId=2, partitionId=3, startRow=0, startCol=6240, endRow=3, endCol=8320)indexNum=-1), comeFromPs=false} com.tencent.angel.ps.server.data.request.UpdateRequest@23] failed 
java.lang.ArrayIndexOutOfBoundsException: 6240
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serializeIntDoubleRow(RowsViewUpdateItem.java:822)
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serializeRow(RowsViewUpdateItem.java:499)
	at com.tencent.angel.psagent.matrix.transport.adapter.RowsViewUpdateItem.serialize(RowsViewUpdateItem.java:70)
	at com.tencent.angel.ps.server.data.request.UpdateRequest.serialize(UpdateRequest.java:127)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient.serializeRequest(MatrixTransportClient.java:2150)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient.access$3300(MatrixTransportClient.java:123)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Requester.sendRequest(MatrixTransportClient.java:2033)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Requester.run(MatrixTransportClient.java:1943)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
my daw.json:
```
{
  "data": {
    "format": "libsvm",
    "indexrange": 1111,
    "numfield": 7,
    "validateratio": 0.1
  },
  "model": {
    "modeltype": "T_DOUBLE_SPARSE_LONGKEY",
    "modelsize": 1111
  },
  "train": {
    "epoch": 10,
    "numupdateperepoch": 10,
    "lr": 0.1,
    "decay": 0.8
  },
  "default_optimizer": {
    "type": "momentum",
    "momentum": 0.9,
    "reg2": 0.01
  },
  "layers": [
    {
      "name": "wide",
      "type": "simpleinputlayer",
      "outputdim": 1,
      "transfunc": "identity"
    },
    {
      "name": "embedding",
      "type": "embedding",
      "numfactors": 8,
      "outputdim": 104
    },
    {
      "name": "fclayer",
      "type": "FCLayer",
      "inputlayer": "embedding",
      "outputdims": [
        100,
        100,
        1
      ],
      "transfuncs": [
        "relu",
        "relu",
        "identity"
      ]
    },
    {
      "name": "sumPooling",
      "type": "SumPooling",
      "outputdim": 1,
      "inputlayers": [
        "wide",
        "fclayer"
      ]
    },
    {
      "name": "simplelosslayer",
      "type": "simplelosslayer",
      "lossfunc": "logloss",
      "inputlayer": "sumPooling"
    }
  ]
}
```
my train data like:
```
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
-1.0 1:1.0 6:1.0 14:1.0 19:1.0 35:1.0 1104:1.0 1108:1.0
```

**Comment by wjlight** [comment]
```
{
      "name": "embedding",
      "type": "embedding",
      "numfactors": 8,
      "outputdim": 104
    },
```
outputdim /  numfactors = numFeature
