### ISSUE TITLE
官方实现的 deepFM 无法正常运行,网络构建失败

### ISSUE THREAD

**Issue by davidxiaozhi** [Angel-ML/angel#947]
---
name: Bug report/Feature request/Question
about: Create a report to help us improve
title: ''官方实现的 deepFM 无法正常运行,网络构建失败"
label: bug/enhancement/question
assignees: ''
---

${ANGEL_HOME}/bin/angel-submit \
  -Dml.epoch.num=20 \
    -Dangel.app.submit.class=com.tencent.angel.ml.core.graphsubmit.GraphRunner \
    -Dml.model.class.name=com.tencent.angel.ml.classification.DeepFM \
    -Dml.feature.index.range=$featureNum \
    -Dml.model.size=$featureNum \
    -Dml.data.validate.ratio=0.1 \
    -Dml.data.type=libsvm \
    -Dml.learn.rate=0.1 \
    -Dml.learn.decay=0.5 \
    -Dml.reg.l2=0.03 \
    -Daction.type=train \
    -Dml.sparseinputlayer.optimizer=ftrl \
    -Dangel.train.data.path=$input_path \
    -Dangel.save.model.path=$output_path \
    -Dangel.workergroup.number=20 \
    -Dangel.worker.memory.mb=20000 \
    -Dangel.worker.task.number=1 \
    -Dangel.ps.number=20 \
    -Dangel.ps.memory.mb=10000 \
    -Dangel.task.data.storage.level=memory \
    -Dangel.job.name=angel_l1 \
    -Dqueue=dev

joy 本地运行出现异常,抛出一下错误

[2020-05-13T09:36:58.293+08:00] [ERROR] angel.utils.AngelRunJar.main(AngelRunJar.java 46) [main] : submit job failed 
scala.MatchError: [Ljava.lang.String;@3fd2322d (of class [Ljava.lang.String;)
 at com.tencent.angel.ml.classification.DeepFM$$anonfun$buildNetwork$1.apply(DeepFM.scala:53)
 at com.tencent.angel.ml.classification.DeepFM$$anonfun$buildNetwork$1.apply(DeepFM.scala:50)
 at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
 at com.tencent.angel.ml.classification.DeepFM.buildNetwork(DeepFM.scala:50)
 at com.tencent.angel.ml.classification.DeepFM.buildNetwork(DeepFM.scala:33)
 at com.tencent.angel.ml.core.graphsubmit.GraphRunner.train(GraphRunner.scala:52)
 at com.tencent.angel.ml.core.MLRunner$class.submit(MLRunner.scala:45)
 at com.tencent.angel.ml.core.graphsubmit.GraphRunner.submit(GraphRunner.scala:30)
 at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:91)
 at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:77)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAs(Subject.java:422)
 at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1830)
 at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:77)
 at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:44)

**Comment by maozida880** [comment]
我司恰好有个项目用这个框架
说下Json submit的心得
1. 在dnn以后，所有的submit都是graph submit，需要这两种类
    -Dangel.app.submit.class=com.tencent.angel.ml.core.graphsubmit.GraphRunner \
    -Dml.model.class.name=com.tencent.angel.ml.core.graphsubmit.AngelModel \
2. Graph定义在json中，
    --angel.ml.conf $daw_json_path \
  坑一：不能用-Dangel.ml.conf $daw_json_path ,实测无效
  坑二： $daw_json_path 需要本地绝对路径

3. graph构建：
   1）考虑特征数，max f
   2)  非零值 ， field num这个非常重要  fn
  3） embedding 大小k
  以deep fm为例，
 如果fn = 30，k=8，
 那么：embedding outputdim = 8*30 = 240
  如果是wide and deep
  同样需要考虑参数，比如C2(30) = 30*29/2
  这个是一般初学者容易在shape中范的问题，导致模型跑不通

我开始遇到这个坑，后来读afm paper在设置参数shape的时候想明白了，发现angel的dnn都需要注意shape的设置

=====================
因为这个框架没人回复，因此，作为热心用户，就互通有无了
希望发扬共享精神，coding share

**Comment by davidxiaozhi** [comment]
@maozida880  十分感谢,这个框架,反馈的问题,确实没有人处理

**Comment by kettlelinna** [comment]
你好，请问这个问题你们解决了吗，我是基于3.0.1-hadoop3分支编译的，但是submit的时候也是报这个错误scala.MatchError: [Ljava.lang.String;@633a2e99 (of class [Ljava.lang.String;)

**Comment by davidxiaozhi** [comment]
> 你好，请问这个问题你们解决了吗，我是基于3.0.1-hadoop3分支编译的，但是submit的时候也是报这个错误scala.MatchError: [Ljava.lang.String;@633a2e99 (of class [Ljava.lang.String;)
默认的 deepFM 官方 实现基于一些常量参数,这些参数配置是有问题的,不明白为什么,不进行测试,建议你自己构造 deepFM
