### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by datawlb** [Angel-ML/angel#991]
**运行的是spark on angel word2vec, angel用的是3.1.0编译的，spark-submit提交集群任务后，出现的错误：**
[2020-07-13 20:25:09] Model created, takes 8.085s
Exception in thread "main" java.lang.NoSuchMethodError: com.tencent.angel.psagent.matrix.MatrixClient.asyncUpdate(Lcom/tencent/angel/ml/matrix/psf/update/base/UpdateFunc;)Ljava/util/concurrent/Future;
	at com.tencent.angel.spark.models.impl.PSMatrixImpl.psfUpdate(PSMatrixImpl.scala:196)
	at com.tencent.angel.spark.ml.embedding.NEModel.psfUpdate(NEModel.scala:192)
	at com.tencent.angel.spark.ml.embedding.NEModel.randomInitialize(NEModel.scala:187)
	at com.tencent.angel.spark.ml.embedding.NEModel.<init>(NEModel.scala:59)
	at com.tencent.angel.spark.ml.embedding.word2vec.Word2VecModel.<init>(Word2VecModel.scala:40)
	at com.tencent.angel.spark.ml.embedding.word2vec.Word2VecModel.<init>(Word2VecModel.scala:43)
	at w2v$.main(w2v.scala:119)
	at w2v.main(w2v.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**119行代码：val model = new Word2VecModel(param)**

**pom.xml文件配置**
部分相关配置：
   <properties>
     <scala.version>2.11.12</scala.version>
     <scala.binary.version>2.11</scala.binary.version>
     <java.version>1.8.0</java.version>
     <spark.version>2.2.0</spark.version>
     <angel.version>3.0.1</angel.version>
   </properties>

    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>angel-ps-mllib</artifactId>
      <version>3.0.1</version>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>angel-ps-examples</artifactId>
      <version>3.0.1</version>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>angel-ps-graph</artifactId>
      <version>3.0.1</version>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>angel-ps-psf</artifactId>
      <version>3.0.1</version>
    </dependency>

    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>spark-on-angel-mllib</artifactId>
      <version>2.4.0</version>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>spark-on-angel-examples</artifactId>
      <version>2.4.0</version>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>spark-on-angel-core</artifactId>
      <version>2.4.0</version>
    </dependency>
    <dependency>
      <groupId>com.tencent.angel</groupId>
      <artifactId>sona</artifactId>
      <version>0.1.0</version>
      <type>pom</type>
    </dependency>

麻烦可以帮忙看下哪里配置错了么，非常感谢！

**Comment by datawlb** [comment]
统一改成2.2.0然后可以了。
